schema = 3

[mod]

[mod."github.com/LK4D4/joincontext"]
version = "v0.0.0-20171026170139-1724345da6d5"
hash = "sha256-SzVsZTDwACO3jmJ5BCEzakv73s2eNLUjhnnwcYSKFT4="

[mod."github.com/PuerkitoBio/purell"]
version = "v1.1.1"
hash = "sha256-Hjf8ZNNdwcRd50A9QNrcCj17gu/6f1iKzVTVrrMrojA="

[mod."github.com/PuerkitoBio/urlesc"]
version = "v0.0.0-20170810143723-de5bf2ad4578"
hash = "sha256-nL0/0QM0Pec83vBlwXvQ8g5SvvZnCQgzD1apxfHNGlg="

[mod."github.com/armon/go-metrics"]
version = "v0.4.0"
hash = "sha256-mB6EFtn8BZ0u9TcJ6QTYw2SNAr4CnTVOMpiRKaoNH7k="

[mod."github.com/armon/go-radix"]
version = "v1.0.0"
hash = "sha256-A5SNdGtw8I6ngk9U3p+rKu6KB7inSngqmdnJl74EM9Q="

[mod."github.com/asaskevich/govalidator"]
version = "v0.0.0-20210307081110-f21760c49a8d"
hash = "sha256-5ZVRCOiNcvpmK3/mhtF1Iy0naPFVVhmXXQmC6eaJExk="

[mod."github.com/cenkalti/backoff/v3"]
version = "v3.2.2"
hash = "sha256-Nam6FNUncrJN+ybAtRg34C8eg/ekPTfqUrkZqsMUBQY="

[mod."github.com/container-storage-interface/spec"]
version = "v1.4.0"
hash = "sha256-ZU7Qxy+9FIWkqpZ+OOBT7gJqsZMdumG4SjvwrmcyAAc="

[mod."github.com/containerd/console"]
version = "v1.0.3"
hash = "sha256-4p4u/rS7G4KKbIcZaVMqE1OtSoNlOpmcYFwO0ZEH/V0="

[mod."github.com/containerd/fifo"]
version = "v1.0.0"
hash = "sha256-OMCD11bviVvsNsYWl4H5LUR7Y/3p2PDXPZLJSlby0tA="

[mod."github.com/containernetworking/cni"]
version = "v1.0.1"
hash = "sha256-NfcbFvbmGOlj5Y5REG2+s1Dn4LJ3RGG1yepn1Ipai9I="

[mod."github.com/containernetworking/plugins"]
version = "v1.0.1"
hash = "sha256-mzp07d8ely0eJIQWFFyFzB/GXQ+LXApQHJo4CE+WW0Y="

[mod."github.com/fatih/color"]
version = "v1.13.0"
hash = "sha256-Xo0zFKLm/9NuChdHDhHoUFo8Oa7Mkb3ezZCu23SfOAk="

[mod."github.com/firecracker-microvm/firecracker-go-sdk"]
version = "v1.0.0"
hash = "sha256-8YxaYHu2STT/m22wAYY/GO0EzRxrLD2bVyBNLkNyeWA="

[mod."github.com/go-ole/go-ole"]
version = "v1.2.6"
hash = "sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs="

[mod."github.com/go-openapi/analysis"]
version = "v0.21.2"
hash = "sha256-jxHyrIO2dC4Uszy+7//7rcWLcGJtoDNj3j5CJOFIsHg="

[mod."github.com/go-openapi/errors"]
version = "v0.20.2"
hash = "sha256-E3DOt2j7zLQXwysf7Act2KzKjUPryF9vswy/M6kJ/nA="

[mod."github.com/go-openapi/jsonpointer"]
version = "v0.19.5"
hash = "sha256-rLyvUdTMeQGeWiVsz2ZeyyFjHomeqd0x+ZR77mxi8Ss="

[mod."github.com/go-openapi/jsonreference"]
version = "v0.19.6"
hash = "sha256-yR7L193fc/w/96+S8l4Nv8NwLq1cDsZiNu3TD195naw="

[mod."github.com/go-openapi/loads"]
version = "v0.21.1"
hash = "sha256-b7n0Usl/pVnlyfvJ1ldG6sdqfxefkIW528Ec3yYzsgo="

[mod."github.com/go-openapi/runtime"]
version = "v0.24.0"
hash = "sha256-A9Z7bdupyXPWtDDc1zmjJOoK5KOKpRfCvp/POFHwWiI="

[mod."github.com/go-openapi/spec"]
version = "v0.20.4"
hash = "sha256-upjAukxFt+zpxxt7+X59910T9JgAn39D/5bl5E0Uib0="

[mod."github.com/go-openapi/strfmt"]
version = "v0.21.2"
hash = "sha256-/6pWCX1OKuWDoma4RAJgDfj+QAcUbRU0oXLt4T0xe68="

[mod."github.com/go-openapi/swag"]
version = "v0.21.1"
hash = "sha256-ZU+S/2wknbRkMxnKKoWILWlcbbo/5mCtx5hR/tyDzb4="

[mod."github.com/go-openapi/validate"]
version = "v0.22.0"
hash = "sha256-zI1lbE8C4ZTWbezhtZR25ArtloLXjvfQplfPS4gI/F0="

[mod."github.com/go-stack/stack"]
version = "v1.8.1"
hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="

[mod."github.com/golang/protobuf"]
version = "v1.5.2"
hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="

[mod."github.com/golang/snappy"]
version = "v0.0.4"
hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="

[mod."github.com/google/uuid"]
version = "v1.3.0"
hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="

[mod."github.com/grpc-ecosystem/go-grpc-middleware"]
version = "v1.2.1-0.20200228141219-3ce3d519df39"
hash = "sha256-YLq6KzQ/RHkBYdJINink2200i0jSksfeYPs5jFvklXA="

[mod."github.com/hashicorp/consul/api"]
version = "v1.13.0"
hash = "sha256-4uYXXR1/cbvWJr1+psVEHEFC3NaGTIqMan3Q3uHG/80="

[mod."github.com/hashicorp/cronexpr"]
version = "v1.1.1"
hash = "sha256-S3tpN5gDUq3T6EkhC8ptN4yRQxNsx3zhgejqq+1XLsg="

[mod."github.com/hashicorp/errwrap"]
version = "v1.1.0"
hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="

[mod."github.com/hashicorp/go-cleanhttp"]
version = "v0.5.2"
hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="

[mod."github.com/hashicorp/go-hclog"]
version = "v1.3.1"
hash = "sha256-ILjAuTrva9fa2++Hg0Z3lSkkKKa5OAM6y44TKIVTE/g="

[mod."github.com/hashicorp/go-immutable-radix"]
version = "v1.3.1"
hash = "sha256-65+A2HiVfS/GV9G+6/TkXXjzXhI/V98e6RlJWjxy+mg="

[mod."github.com/hashicorp/go-msgpack"]
version = "v1.1.5"
hash = "sha256-qMdNrl9AYvQqROlrNv33hYj76nhJsM29z6u2wiDlCr0="

[mod."github.com/hashicorp/go-multierror"]
version = "v1.1.1"
hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="

[mod."github.com/hashicorp/go-plugin"]
version = "v1.4.3"
hash = "sha256-3mRuaLOHGNKCfxqNYI5WSl5u2jdMYd/EoIbv4nZshEI="

[mod."github.com/hashicorp/go-retryablehttp"]
version = "v0.7.0"
hash = "sha256-1KOm+BiuNUvJC+Y5qlwdcUyLBcaI43nXXtuT5fFRBt8="

[mod."github.com/hashicorp/go-rootcerts"]
version = "v1.0.2"
hash = "sha256-prifkrFs+lawGTig3GwxddR0QM9E1+IpgZWCKoOnS5M="

[mod."github.com/hashicorp/go-secure-stdlib/mlock"]
version = "v0.1.2"
hash = "sha256-Vxb4ENvV7HeQ5L/shm19IC5yMowP3E7EubQgW7lPj7s="

[mod."github.com/hashicorp/go-secure-stdlib/parseutil"]
version = "v0.1.4"
hash = "sha256-v/qHM76rjnX10WCUgPycs5dajePk1qU4yt0XFHbnF1Q="

[mod."github.com/hashicorp/go-secure-stdlib/strutil"]
version = "v0.1.2"
hash = "sha256-UmCMzjamCW1d9KNvNzELqKf1ElHOXPz+ZtdJkI+DV0A="

[mod."github.com/hashicorp/go-set"]
version = "v0.1.2"
hash = "sha256-0FD9/FS8bf1/50EhG0hMholhHhBFRfveEqTu9iRp/W4="

[mod."github.com/hashicorp/go-sockaddr"]
version = "v1.0.2"
hash = "sha256-bshn2I074/pnQ8gZU5RsfQRTrIvMC459bOfd/O/dHeo="

[mod."github.com/hashicorp/go-uuid"]
version = "v1.0.2"
hash = "sha256-SsIZNWnnjuPbiclz2bs9AKWHvpuVsrFUW2CzAVSx8qs="

[mod."github.com/hashicorp/go-version"]
version = "v1.4.0"
hash = "sha256-WhSIsdN9RjM9rMBVPboxk4uEJQXUx5lW7gpNu/hDSNA="

[mod."github.com/hashicorp/golang-lru"]
version = "v0.5.4"
hash = "sha256-1skUMZX+iIf66J1TBVYGWO1OWwQcaoXut3mne331q+k="

[mod."github.com/hashicorp/hcl"]
version = "v1.0.1-vault-3"
hash = "sha256-stsldCozk7G4coPNVndIyPa4aAjdWjs7qjLaEet6vZA="

[mod."github.com/hashicorp/nomad"]
version = "v1.3.5"
hash = "sha256-qK3WL6uv2hfazD6zOhUxxmmLxlEOBKvAR1Jp+hVqOhA="

[mod."github.com/hashicorp/raft"]
version = "v1.3.9"
hash = "sha256-bhaRTFJ92B44dExiP75XXHgdB0nYUu7bDHsZ03fN2Xc="

[mod."github.com/hashicorp/serf"]
version = "v0.9.7"
hash = "sha256-nspC/BZwLmF2Lw41s68DmZ4kFsMeB3hvH7ZCLtdl2OM="

[mod."github.com/hashicorp/vault/api"]
version = "v1.4.1"
hash = "sha256-hcu4Yv6P8U5LfzP5x6ufaEtNe0xdh+Tc5PLgqxTsYpo="

[mod."github.com/hashicorp/vault/sdk"]
version = "v0.4.1"
hash = "sha256-WqSsjIZr1ZwwX5KtP6a1hqam8t0f7kB6I8i7oEZTo2k="

[mod."github.com/hashicorp/yamux"]
version = "v0.0.0-20211028200310-0bc27b27de87"
hash = "sha256-awp0ed3Etk20b8QfolUPRvBB7ddxfMtnQiJMtp7rf6E="

[mod."github.com/hpcloud/tail"]
version = "v1.0.1-0.20170814160653-37f427138745"
hash = "sha256-7NWKcNW2+0c/r1+rTftxhRChavUuhaQmBMLWc96v90s="

[mod."github.com/josharian/intern"]
version = "v1.0.0"
hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="

[mod."github.com/lufia/plan9stats"]
version = "v0.0.0-20211012122336-39d0f177ccd0"
hash = "sha256-thb+rkDx5IeWMgw5/5jgu5gZ+6RjJAUXeMgSkJHhRlA="

[mod."github.com/mailru/easyjson"]
version = "v0.7.7"
hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="

[mod."github.com/mattn/go-colorable"]
version = "v0.1.12"
hash = "sha256-Y1vCt0ShrCz4wSmwsppCfeLPLKrWusc2zM2lUFwDMyI="

[mod."github.com/mattn/go-isatty"]
version = "v0.0.14"
hash = "sha256-e8zn5eCVh/B1HOP1PGXeXH0bGkIV0vKYP9KLwZni5as="

[mod."github.com/miekg/dns"]
version = "v1.1.41"
hash = "sha256-SzL4RdPRR0SUFKU2ykXRApZ2rZ8LrHlhBP0L443oXxQ="

[mod."github.com/mitchellh/copystructure"]
version = "v1.2.0"
hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="

[mod."github.com/mitchellh/go-homedir"]
version = "v1.1.0"
hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="

[mod."github.com/mitchellh/go-testing-interface"]
version = "v1.14.1"
hash = "sha256-TMGi38D13BEVN5cpeKDzKRIgLclm4ErOG+JEyqJrN/c="

[mod."github.com/mitchellh/hashstructure"]
version = "v1.1.0"
hash = "sha256-dNPVpLRsCa2XZHlCRRtkpBVqb8rpHIocpFPNCqZg2EY="

[mod."github.com/mitchellh/mapstructure"]
version = "v1.5.0"
hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="

[mod."github.com/mitchellh/reflectwalk"]
version = "v1.0.2"
hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="

[mod."github.com/moby/sys/mount"]
version = "v0.3.0"
hash = "sha256-ic+jPKl7ReVtaJNxDn0alBfad2vmo/9ir6YoEOEfeSs="

[mod."github.com/moby/sys/mountinfo"]
version = "v0.6.0"
hash = "sha256-11lPRC9+rM0mJPWFGHhUb1o+KxZiWwzQQkQepODRFug="

[mod."github.com/oklog/run"]
version = "v1.1.0"
hash = "sha256-U4IS0keJa4BSBSeEBqtIV1Zg6N4b0zFiKfzN9ua4pWQ="

[mod."github.com/oklog/ulid"]
version = "v1.3.1"
hash = "sha256-LNn883rYNiaoY9sGEPIzlMRx5UwGThdYTjXqfzeGc9k="

[mod."github.com/opentracing/opentracing-go"]
version = "v1.2.0"
hash = "sha256-kKTKFGXOsCF6QdVzI++GgaRzv2W+kWq5uDXOJChvLxM="

[mod."github.com/pierrec/lz4"]
version = "v2.6.1+incompatible"
hash = "sha256-5+4i5SN97wG71knAF9eUgEEG5k03HW4wPnAdPd6JSfE="

[mod."github.com/pkg/errors"]
version = "v0.9.1"
hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="

[mod."github.com/power-devops/perfstat"]
version = "v0.0.0-20210106213030-5aafc221ea8c"
hash = "sha256-ywykDYuqcMt0TvZOz1l9Z6Z2JMTYQw8cP2fT8AtpmX4="

[mod."github.com/ryanuber/go-glob"]
version = "v1.0.0"
hash = "sha256-YkMl1utwUhi3E0sHK23ISpAsPyj4+KeXyXKoFYGXGVY="

[mod."github.com/shirou/gopsutil"]
version = "v2.21.11+incompatible"
hash = "sha256-tcH5zN94yZhKtg8wAUfojlqdyguifuPTBLPso3KF7QA="

[mod."github.com/shirou/gopsutil/v3"]
version = "v3.21.12"
hash = "sha256-yjpVhocVdzjVFZXoRaPxJ0/3qVqMsssPySZQqelHuV0="

[mod."github.com/sirupsen/logrus"]
version = "v1.9.0"
hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="

[mod."github.com/tklauser/go-sysconf"]
version = "v0.3.9"
hash = "sha256-hZvD7n9awG8lwvgfLbyXkOc6Vu49xIqAWDffl+1bMC4="

[mod."github.com/tklauser/numcpus"]
version = "v0.3.0"
hash = "sha256-rKRpPvlz3+U+lbSkbmKjnDGcngGIXSqyAfiH9xHPT3k="

[mod."github.com/vishvananda/netlink"]
version = "v1.1.1-0.20210330154013-f5de75959ad5"
hash = "sha256-uJk8UocElSSEoX6TAgMOWAb1YeK0fWIeCpi685uXcdE="

[mod."github.com/vishvananda/netns"]
version = "v0.0.0-20210104183010-2eb08e3e575f"
hash = "sha256-XM9giEeO//I/8SgHLuSWtJAvMftd6GHdzKHoy3YLrjQ="

[mod."github.com/vmihailenco/msgpack/v4"]
version = "v4.3.12"
hash = "sha256-z+66be90XMeCMrHQyJEDhuolZqPKArYWKMC6ss7cKio="

[mod."github.com/vmihailenco/tagparser"]
version = "v0.1.1"
hash = "sha256-cP3Mk2VxcTz4dGK5zeAuW+ibm3UYIBqhM1Z82MciA2U="

[mod."github.com/yusufpapurcu/wmi"]
version = "v1.2.2"
hash = "sha256-Rno6F82JIeglBobQl6YKl3U6+FvWXmFavJlzpOJgoXI="

[mod."github.com/zclconf/go-cty"]
version = "v1.8.0"
hash = "sha256-Sf4mCSBV8e53x8nI0YPgZHivNWmUseWc26AtTdcUv4c="

[mod."go.mongodb.org/mongo-driver"]
version = "v1.8.3"
hash = "sha256-RlEByqZe5m+AXjDqOk5qgzsxXziz1hw1PV5ZoejRxCk="

[mod."go.uber.org/atomic"]
version = "v1.9.0"
hash = "sha256-D8OtLaViqPShz1w8ijhIHmjw9xVaRu0qD2hXKj63r4Q="

[mod."golang.org/x/crypto"]
version = "v0.0.0-20220622213112-05595931fe9d"
hash = "sha256-2c4wvwiQ0DJSJsApfmNoxCxx1siRCiJvW9hhrGlcvds="

[mod."golang.org/x/exp"]
version = "v0.0.0-20220609121020-a51bd0440498"
hash = "sha256-ihGRNkqqwowFsEfu3Sy5FB6xeh/2gsmasvDfqARmb8Q="

[mod."golang.org/x/net"]
version = "v0.0.0-20220225172249-27dd8689420f"
hash = "sha256-4SnOIK+qHMdSaJHI89ayYWLK9hBiL/zrqtRgexWo0TY="

[mod."golang.org/x/sys"]
version = "v0.0.0-20220715151400-c0bba94af5f8"
hash = "sha256-8LGu1Rwel+ZWaOXHjOxoQDthPPDpJxWD9SoXdCJQq04="

[mod."golang.org/x/text"]
version = "v0.3.7"
hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="

[mod."golang.org/x/time"]
version = "v0.0.0-20220224211638-0e9765cccd65"
hash = "sha256-ugBhklXE3xsTvAO0xB18x71NhaTZj8FIMS+6lzZpmsk="

[mod."google.golang.org/appengine"]
version = "v1.6.7"
hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="

[mod."google.golang.org/genproto"]
version = "v0.0.0-20220314164441-57ef72a4c106"
hash = "sha256-NoL5PQfw61qp8geXqQmFKfsEFtjJ4xefhMsmVX+DyV8="

[mod."google.golang.org/grpc"]
version = "v1.45.0"
hash = "sha256-9UGs650/hIRqwGbZjJSL4GiqVnzu0V5EhnuZ3qdvV84="

[mod."google.golang.org/protobuf"]
version = "v1.27.1"
hash = "sha256-klLGFG4InPHIBDgisRph7H/02D5rBVx0ho9rZCRyLbk="

[mod."gopkg.in/fsnotify.v1"]
version = "v1.4.7"
hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="

[mod."gopkg.in/square/go-jose.v2"]
version = "v2.6.0"
hash = "sha256-GRzbqF2tkyZ8/XEDkGNxF7TxBxd3z3umy/zD6jqGNqw="

[mod."gopkg.in/tomb.v1"]
version = "v1.0.0-20141024135613-dd632973f1e7"
hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="

[mod."gopkg.in/yaml.v2"]
version = "v2.4.0"
hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
