schema = 3

[mod]

[mod."github.com/alecthomas/assert/v2"]
version = "v2.1.0"
hash = "sha256-CkOPI9mqXxC0efFP90UqAMOiBExWlHYhYqtk7/QooNA="

[mod."github.com/alecthomas/kong"]
version = "v0.7.1"
hash = "sha256-Wyg4T/TX2Le7SsbA3YFX1LVRsc8+7e8JPf1elBs/jdo="

[mod."github.com/alecthomas/repr"]
version = "v0.1.0"
hash = "sha256-mY3bqA2Y+aWbD8WjSoPA7+fJ+nsVs8QJ8aA5iavNO6I="

[mod."github.com/davecgh/go-spew"]
version = "v1.1.1"
hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="

[mod."github.com/gin-contrib/sse"]
version = "v0.1.0"
hash = "sha256-zYbMTao+1F+385Lvsba9roLmmt9eYqr57sUWo0LCVhw="

[mod."github.com/gin-gonic/gin"]
version = "v1.7.7"
hash = "sha256-/9IwMXTVcZZOOkVKTlefXRgBL39XzHE7RMmgeKf1Nds="

[mod."github.com/go-playground/assert/v2"]
version = "v2.0.1"
hash = "sha256-n6OoNqwhTXNv9M4Q2pj+AjwUFNAQmiHzb+0XQDRhibI="

[mod."github.com/go-playground/locales"]
version = "v0.13.0"
hash = "sha256-7h4uxekzu3iVoOzF3LxKJiJLhjLv9zErcnVovedlzWM="

[mod."github.com/go-playground/universal-translator"]
version = "v0.17.0"
hash = "sha256-5lO55OaLeK7vilE0Bgns+lCK+st4XTZSJzuKsXRUsf0="

[mod."github.com/go-playground/validator/v10"]
version = "v10.4.1"
hash = "sha256-IVzbJrF/Hegs0bw0aeEhg+7ac79gTg/pap8DhbnQj1w="

[mod."github.com/golang/protobuf"]
version = "v1.3.3"
hash = "sha256-iN3MrKtLrS/Fm5GJVuggD0ue0CFm0sfGNRMRsKU5130="

[mod."github.com/google/gofuzz"]
version = "v1.0.0"
hash = "sha256-ZvgcSQt4kMwS6nvPp3jrlCHSH3bky1oBD6kytnEa5GM="

[mod."github.com/hexops/gotextdiff"]
version = "v1.0.3"
hash = "sha256-wVs5uJs2KHU1HnDCDdSe0vIgNZylvs8oNidDxwA3+O0="

[mod."github.com/json-iterator/go"]
version = "v1.1.9"
hash = "sha256-BgQjHEs+54yxYrv/TkNj3Go1ZkdOmIyGXZys6HLLolE="

[mod."github.com/leodido/go-urn"]
version = "v1.2.0"
hash = "sha256-NW7kxG9syegZOrRyHz877IhFEN2I4GMDBSgEBucOj7Q="

[mod."github.com/mattn/go-isatty"]
version = "v0.0.12"
hash = "sha256-noBpx3K4sa7tJcPpSUh+h7wJ8CRfrObaraKC2dE6VWU="

[mod."github.com/modern-go/concurrent"]
version = "v0.0.0-20180228061459-e0a39a4cb421"
hash = "sha256-+bdeHUArnpkk4eMQIwXm9K249NkpwAjoTrXrGn/4VUE="

[mod."github.com/modern-go/reflect2"]
version = "v0.0.0-20180701023420-4b7aa43c6742"
hash = "sha256-RyIwgrPwtd4lNjLGkBVxRvu5IdXLDqf5F69QWLm0zLw="

[mod."github.com/pmezard/go-difflib"]
version = "v1.0.0"
hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="

[mod."github.com/sashabaranov/go-gpt3"]
version = "v1.3.0"
hash = "sha256-/uVDYemCRh0+mRa9S8h/5xbo63wcn17ks8l9+zQqXno="

[mod."github.com/stretchr/objx"]
version = "v0.1.0"
hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="

[mod."github.com/stretchr/testify"]
version = "v1.4.0"
hash = "sha256-yJw5uyO9WCd1/fxFK/1fYch8WKKALoqVFENX8Nt92fY="

[mod."github.com/ugorji/go"]
version = "v1.1.7"
hash = "sha256-k9HKvzLh9r6Q4l0q5kyeDgc0rnH1VxqmY4EPiFyNL40="

[mod."github.com/ugorji/go/codec"]
version = "v1.1.7"
hash = "sha256-fulAoEEqegVZP4qtPJAD6/vw/AeI00i27tslP2c/7ko="

[mod."github.com/yuin/goldmark"]
version = "v1.4.13"
hash = "sha256-GVwFKZY6moIS6I0ZGuio/WtDif+lkZRfqWS6b4AAJyI="

[mod."golang.org/x/crypto"]
version = "v0.0.0-20210921155107-089bfa567519"
hash = "sha256-62Qtoqu7AxoxpZFd+75qXC0naixAct3rWsJd0nSgMCU="

[mod."golang.org/x/mod"]
version = "v0.8.0"
hash = "sha256-cgtmxQA937+MdXUiPrVeDvRoqhxD4hvIbtXAjK2SM8U="

[mod."golang.org/x/net"]
version = "v0.8.0"
hash = "sha256-2cOtqa7aJ5mn64kZ+8+PVjJ4uGbhpXTpC1vm/+iaZzM="

[mod."golang.org/x/sync"]
version = "v0.1.0"
hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="

[mod."golang.org/x/sys"]
version = "v0.6.0"
hash = "sha256-zAgxiTuL24sGhbXrna9R1UYqLQh46ldztpumOScmduY="

[mod."golang.org/x/term"]
version = "v0.6.0"
hash = "sha256-Ao0yXpwY8GyG+/23dVfJUYrfEfNUTES3RF45v1VhUAk="

[mod."golang.org/x/text"]
version = "v0.8.0"
hash = "sha256-hgWFnT01DRmywBEXKYEVaOee7i6z8Ydz7zGbjcWwOgI="

[mod."golang.org/x/tools"]
version = "v0.6.0"
hash = "sha256-J0q+C3WDTK9yyHX90FV6qr6n9H07YglYg1p4H3MqyH4="

[mod."golang.org/x/xerrors"]
version = "v0.0.0-20190717185122-a985d3407aa7"
hash = "sha256-kj2qs47n+a4gtKXHJN3U9gcSQ3BozjzYu7EphXjJnwM="

[mod."gopkg.in/check.v1"]
version = "v0.0.0-20161208181325-20d25e280405"
hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="

[mod."gopkg.in/yaml.v2"]
version = "v2.2.8"
hash = "sha256-/KoaoUbFCm3r8nZyPaWZshMVTM2iSebS5kz/5rc+zsY="
