# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aim = {
    pname = "aim";
    version = "v3.17.5";
    src = fetchFromGitHub {
      owner = "aimhubio";
      repo = "aim";
      rev = "v3.17.5";
      fetchSubmodules = false;
      sha256 = "sha256-IGA2Ol2LkRQvWqjwIv1+ymqDoobQmQjRvnBie41OL+Q=";
    };
  };
  broker-to-json = {
    pname = "broker-to-json";
    version = "v_02";
    src = fetchFromGitHub {
      owner = "grigorescu";
      repo = "broker-to-json";
      rev = "v_02";
      fetchSubmodules = false;
      sha256 = "sha256-SROcIR2P5ixk4yDVwkUJczdbuU4STpmTyLNBCj6dEtg=";
    };
  };
  btest = {
    pname = "btest";
    version = "1.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/b/btest/btest-1.1.tar.gz";
      sha256 = "sha256-MS7vhzqr2go5zm5xbBVT4DR46qBoZFb2MnAgXgSfprs=";
    };
  };
  choochoo = {
    pname = "choochoo";
    version = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
    src = fetchFromGitHub {
      owner = "andrewcooke";
      repo = "choochoo";
      rev = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
      fetchSubmodules = false;
      sha256 = "sha256-/PjfY1thoILxpu3/PTmFRfzR4eFgraLbTXpVM54GXJk=";
    };
    date = "2021-09-12";
  };
  cliche = {
    pname = "cliche";
    version = "3621191561579f93867417c14b6bc25583d00c0d";
    src = fetchFromGitHub {
      owner = "kootenpv";
      repo = "cliche";
      rev = "3621191561579f93867417c14b6bc25583d00c0d";
      fetchSubmodules = false;
      sha256 = "sha256-K/39gTrZrZ1Nsrv9zYQV7ID3r8V1LcAJeHUQbq8Eqo0=";
    };
    date = "2023-11-23";
  };
  durationpy = {
    pname = "durationpy";
    version = "0.5";
    src = fetchurl {
      url = "https://pypi.org/packages/source/d/durationpy/durationpy-0.5.tar.gz";
      sha256 = "sha256-XvlBa1J7UNci80ZVvs+3Xkkijrgvh7hV7RkRszFLVAg=";
    };
  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
    src = fetchFromGitHub {
      owner = "esnet";
      repo = "eZeeKonfigurator";
      rev = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
      fetchSubmodules = false;
      sha256 = "sha256-K7PLVVesjv27dhYyRaWItfnsh+p6FTMFOXVE576a01I=";
    };
    date = "2022-07-05";
  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchFromGitHub {
      owner = "esnet";
      repo = "eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      sha256 = "sha256-b2QqmduoyohAIOJnZP/Vnt9FdmoOebDfmaTs5SNVoAg=";
    };
    date = "2021-07-01";
  };
  elastalert2 = {
    pname = "elastalert2";
    version = "bfbdd4dcbdc3e84a2f5b612d5ba344dd09ce6254";
    src = fetchFromGitHub {
      owner = "jertel";
      repo = "elastalert2";
      rev = "bfbdd4dcbdc3e84a2f5b612d5ba344dd09ce6254";
      fetchSubmodules = false;
      sha256 = "sha256-1XjoMYe8eTHI2PptaZQ9oeP8HIE4q7L+VtgRFaNVVys=";
    };
    date = "2023-11-24";
  };
  fastai = {
    pname = "fastai";
    version = "96f0e2027c8fd82eef40984faf14c1c81e0eb031";
    src = fetchFromGitHub {
      owner = "fastai";
      repo = "fastai";
      rev = "96f0e2027c8fd82eef40984faf14c1c81e0eb031";
      fetchSubmodules = false;
      sha256 = "sha256-EUZy7pEBlPBZpfzTh5ENWeGlCdJeaICZ2Ic2mw355wA=";
    };
    date = "2023-11-02";
  };
  fastcore = {
    pname = "fastcore";
    version = "1cb38a0d8d97091cd3365e669e39db64be40aaa2";
    src = fetchFromGitHub {
      owner = "fastai";
      repo = "fastcore";
      rev = "1cb38a0d8d97091cd3365e669e39db64be40aaa2";
      fetchSubmodules = false;
      sha256 = "sha256-QhzzXkNol3OfZ/gCBTsfwsbjWbkQ8ZpYMszBQK/2oUU=";
    };
    date = "2023-06-25";
  };
  fastdownload = {
    pname = "fastdownload";
    version = "9c729f96be9b930054dadfc1598964e61664f434";
    src = fetchFromGitHub {
      owner = "fastai";
      repo = "fastdownload";
      rev = "9c729f96be9b930054dadfc1598964e61664f434";
      fetchSubmodules = false;
      sha256 = "sha256-LCI5eP7SYKp2RP+Mk8mfm4sNITgCn1tkqXXpNdqenqc=";
    };
    date = "2022-07-08";
  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.3";
    src = fetchurl {
      url = "https://pypi.org/packages/source/f/fastprogress/fastprogress-1.0.3.tar.gz";
      sha256 = "sha256-ehfStDiJD4OMBI7vzjLE3tRxl+zI6gQs7MM9PeuAIvU=";
    };
  };
  polars = {
    pname = "polars";
    version = "py-0.19.16";
    src = fetchFromGitHub {
      owner = "pola-rs";
      repo = "polars";
      rev = "py-0.19.16";
      fetchSubmodules = false;
      sha256 = "sha256-nKLObPGcuTYhUz3A3PhFu5kMymDh8vQzm8zIcxWGWPs=";
    };
  };
  py-tree-sitter = {
    pname = "py-tree-sitter";
    version = "dd45124a09dee409f452f949f98882ae4a612120";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "py-tree-sitter";
      rev = "dd45124a09dee409f452f949f98882ae4a612120";
      fetchSubmodules = true;
      sha256 = "sha256-t+cTBszZcyPPW+Aqk+R91X/TkOaZXxUifmNYl63tFQE=";
    };
    date = "2023-11-15";
  };
  sh = {
    pname = "sh";
    version = "2.0.6";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/sh/sh-2.0.6.tar.gz";
      sha256 = "sha256-mymY8xPyAcd34sAGHwsTZ0lwl+8TOIWVvhR+KgC/e6E=";
    };
  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchFromGitHub {
      owner = "NullHypothesis";
      repo = "sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      sha256 = "sha256-vIOibQuMauVhkxgR9QaL+pbocY7xgyamMeOhtKmye70=";
    };
    date = "2019-03-26";
  };
  tiny-cuda-nn = {
    pname = "tiny-cuda-nn";
    version = "v1.6";
    src = fetchFromGitHub {
      owner = "NVlabs";
      repo = "tiny-cuda-nn";
      rev = "v1.6";
      fetchSubmodules = false;
      sha256 = "sha256-5qNVMK0PCH8E1kQqDcGCs+i787Vidq4y436LnH36yD0=";
    };
  };
  vailyn = {
    pname = "vailyn";
    version = "v3.3.2-1";
    src = fetchFromGitHub {
      owner = "VainlyStrain";
      repo = "Vailyn";
      rev = "v3.3.2-1";
      fetchSubmodules = false;
      sha256 = "sha256-eHnqfL6Nt0FDyIoZ4RhwB29h3r6ctVQKAGCeZkOk5yo=";
    };
  };
  vault-cli = {
    pname = "vault-cli";
    version = "0142476bcfda52876951f49b0990ac1d85377d3a";
    src = fetchFromGitHub {
      owner = "peopledoc";
      repo = "vault-cli";
      rev = "0142476bcfda52876951f49b0990ac1d85377d3a";
      fetchSubmodules = false;
      sha256 = "sha256-/YNBI1IknygmqKy5JMCS63AX581YY5wqE1KN75rBPH0=";
    };
    date = "2022-01-27";
  };
  zat = {
    pname = "zat";
    version = "36685ae54bb4db6444f2efa36ad40a9247212efd";
    src = fetchFromGitHub {
      owner = "SuperCowPowers";
      repo = "zat";
      rev = "36685ae54bb4db6444f2efa36ad40a9247212efd";
      fetchSubmodules = false;
      sha256 = "sha256-g6rC/uAOVP3uA2e9JJRI4yi5TwnTyEDh1dJ9e1030QA=";
    };
    date = "2023-09-07";
  };
  zed = {
    pname = "zed";
    version = "f530788f732472ed060ab320ea0e175690c47b4d";
    src = fetchFromGitHub {
      owner = "brimdata";
      repo = "zed";
      rev = "f530788f732472ed060ab320ea0e175690c47b4d";
      fetchSubmodules = false;
      sha256 = "sha256-b7X4inBKYDafDH+VE8OoNx3SF7NjpvA6hq/7ABEsiPw=";
    };
    date = "2023-11-22";
  };
  zeekscript = {
    pname = "zeekscript";
    version = "ed16219b20ed02f63806b8d60197e161da1383da";
    src = fetchFromGitHub {
      owner = "zeek";
      repo = "zeekscript";
      rev = "ed16219b20ed02f63806b8d60197e161da1383da";
      fetchSubmodules = true;
      sha256 = "sha256-jmIswaq6nNDbjYkuraDtAih+odCOZtY7hvBHPmDiMCw=";
    };
    date = "2023-11-07";
  };
}
