schema = 3

[mod]

[mod."github.com/JohnCGriffin/overflow"]
version = "v0.0.0-20211019200055-46fa312c352c"
hash = "sha256-BDp0GykmeDlBjVPZVM3rpmsfwrvpqKPqusIZG5xY7Wo="

[mod."github.com/agnivade/levenshtein"]
version = "v1.1.1"
hash = "sha256-tgv2s8XIcWjscv1pP87TOIUV4vADT2px1Lo/MQCTBjM="

[mod."github.com/alecthomas/units"]
version = "v0.0.0-20190924025748-f65c72e2690d"
hash = "sha256-bC2xzCx7LOE8pYbWnzA6evO8MZk9ueDdvQHUUU/FXhI="

[mod."github.com/andybalholm/brotli"]
version = "v1.0.4"
hash = "sha256-gAnPRdGP4yna4hiRIEDyBtDOVJqd7RU27wlPu96Rdf8="

[mod."github.com/apache/arrow/go/v11"]
version = "v11.0.0-20221214174703-0dfec8e98f4f"
hash = "sha256-kH5EyfEXVgEj8/CX41gci+23E7KpVC789QwViA/ctiw="

[mod."github.com/apache/thrift"]
version = "v0.16.0"
hash = "sha256-4jsjTxU5CZ6feurBx3pIY2JF5FsoMewVOQHeVtgHkdA="

[mod."github.com/araddon/dateparse"]
version = "v0.0.0-20210429162001-6b43995a97de"
hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="

[mod."github.com/aws/aws-sdk-go"]
version = "v1.36.17"
hash = "sha256-jUasRPchEoCFbnEAV1k61nxLRP9bynig/qriFeuLhQI="

[mod."github.com/axiomhq/hyperloglog"]
version = "v0.0.0-20191112132149-a4c4c47bc57f"
hash = "sha256-mhThkWjecSomS8pP6uJDYnUq/isLLwhwsENXYKHvkl8="

[mod."github.com/beorn7/perks"]
version = "v1.0.1"
hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="

[mod."github.com/cespare/xxhash/v2"]
version = "v2.1.2"
hash = "sha256-YV9SmXDtmmgQylQUfrUgQLAPfqYexcHxegMBT+IX9qM="

[mod."github.com/davecgh/go-spew"]
version = "v1.1.1"
hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="

[mod."github.com/dgryski/go-metro"]
version = "v0.0.0-20180109044635-280f6062b5bc"
hash = "sha256-WdJuGgX7NKfocz6IhMcClfx30ZnxAPjfZTRAOr2eAqk="

[mod."github.com/dgryski/go-rendezvous"]
version = "v0.0.0-20200823014737-9f7001d12a5f"
hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="

[mod."github.com/fraugster/parquet-go"]
version = "v0.10.1-0.20220222153523-e6b70a8a7212"
hash = "sha256-eo9iwQHr1ox608jnuoYBtFmKxv923mg+H3KlECv9Iqk="

[mod."github.com/go-redis/redis/v8"]
version = "v8.4.11"
hash = "sha256-+xxGAt4fAD8NO+W+CHFNPxqsqd5jIXeAWKRukxUu82o="

[mod."github.com/goccy/go-json"]
version = "v0.9.11"
hash = "sha256-sY9WBxPB+scdLNg7k4PMxEapi1ZCU9GclZuVm8EzD9M="

[mod."github.com/golang-jwt/jwt/v4"]
version = "v4.4.3"
hash = "sha256-mnvfZJP7Cu0ibnlvGG+BAKvgGH74kHZCrzHTAMYHZCE="

[mod."github.com/golang/mock"]
version = "v1.5.0"
hash = "sha256-DwsajUB1hknylVqmvPyD+z5jjHiP4D+dNv9FUiuYYnU="

[mod."github.com/golang/protobuf"]
version = "v1.5.2"
hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="

[mod."github.com/golang/snappy"]
version = "v0.0.4"
hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="

[mod."github.com/google/flatbuffers"]
version = "v2.0.8+incompatible"
hash = "sha256-10N9pnZB4J5IEaR8fTLH438DtDIeIAaxH86D1xtT+x4="

[mod."github.com/gorilla/mux"]
version = "v1.7.5-0.20200711200521-98cb6bf42e08"
hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="

[mod."github.com/gosuri/uilive"]
version = "v0.0.4"
hash = "sha256-T81PkAKf0kl2jeF4HG0AehaDsGyzW6ZVQyDtSjjonV8="

[mod."github.com/hashicorp/golang-lru/v2"]
version = "v2.0.1"
hash = "sha256-z+zVGv1kC/MvFpBHWBWYX5wwErHPHGMpIUyrx3aqnA4="

[mod."github.com/jmespath/go-jmespath"]
version = "v0.4.0"
hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="

[mod."github.com/klauspost/asmfmt"]
version = "v1.3.2"
hash = "sha256-YxIVqPGsqxvOY0Qz4Jw5FuO9IbplCICjChosnHrSCgc="

[mod."github.com/klauspost/compress"]
version = "v1.15.9"
hash = "sha256-ctPxlVq0c/SoNPVsP66RjxUjTHys3diW2Apxjyc9WdE="

[mod."github.com/klauspost/cpuid/v2"]
version = "v2.0.9"
hash = "sha256-0rHlHzEVaDdkVbRJDhnAJjfJUmAHOYjXN5u7VoCi5uk="

[mod."github.com/kr/text"]
version = "v0.2.0"
hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="

[mod."github.com/mattn/go-isatty"]
version = "v0.0.16"
hash = "sha256-YMaPZvShDfA98vqw1+zWWl7M1IT4nHPGBrAt7kHo8Iw="

[mod."github.com/mattn/go-runewidth"]
version = "v0.0.10"
hash = "sha256-S/ppuBSisvWwrRp36vFPN7xAVowYReIY5KySiI1FS2o="

[mod."github.com/matttproud/golang_protobuf_extensions"]
version = "v1.0.1"
hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="

[mod."github.com/minio/asm2plan9s"]
version = "v0.0.0-20200509001527-cdd76441f9d8"
hash = "sha256-b7krSCSjria+MNffLmH2D0u7cK2DamSkZ8dj928sw0Q="

[mod."github.com/minio/c2goasm"]
version = "v0.0.0-20190812172519-36a3d3bbc4f3"
hash = "sha256-hRcCFqIOQ76+XB9qMQTwGHIZ/4q1mlYnSvzBP/w/CVs="

[mod."github.com/paulbellamy/ratecounter"]
version = "v0.2.0"
hash = "sha256-yZGMzwo5Gadrb04WJfVNGzkWYEjtjJ+yvRVtw1QwjHw="

[mod."github.com/pbnjay/memory"]
version = "v0.0.0-20190104145345-974d429e7ae4"
hash = "sha256-eM4qoRupv0Py1TqMn/wSFEDeICuq/twUviDZpm95X00="

[mod."github.com/peterh/liner"]
version = "v1.1.0"
hash = "sha256-YSDIUdBUbtO6Wpf1/zadI/+z3yGlvYP4WHUM68rhPJM="

[mod."github.com/pierrec/lz4/v4"]
version = "v4.1.17"
hash = "sha256-36L+GNhRrHBCyhbHCqweCk5rfmggdRtHqH6g5m1ViQI="

[mod."github.com/pkg/browser"]
version = "v0.0.0-20210911075715-681adbf594b8"
hash = "sha256-JZhcXaILA6QFOYnVdiHbKQuKABQNAE0VhMWZXsZngLQ="

[mod."github.com/pmezard/go-difflib"]
version = "v1.0.0"
hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="

[mod."github.com/prometheus/client_golang"]
version = "v1.14.0"
hash = "sha256-dpgGV8C30ZCn7b9mQ+Ye2AfPXTIuHLQbl2olMKzJKxA="

[mod."github.com/prometheus/client_model"]
version = "v0.3.0"
hash = "sha256-vP+miJfsoK5UG9eug8z/bhAMj3bwg66T2vIh8WHoOKU="

[mod."github.com/prometheus/common"]
version = "v0.37.0"
hash = "sha256-B2v0WsP8uKWYBpZcrog/sQXStIXwWZcVLmfPgnh1ZZA="

[mod."github.com/prometheus/procfs"]
version = "v0.8.0"
hash = "sha256-hgrilokQsXCOCCvwgOSfuErxoFAQpXM/+zNJKcMVHyM="

[mod."github.com/rivo/uniseg"]
version = "v0.1.0"
hash = "sha256-hfMUzdGA1Ept71D3t++FTM55dwWxN/g7DcvQ0G9glzo="

[mod."github.com/rs/cors"]
version = "v1.8.0"
hash = "sha256-+SW32FBrPDBryzmdN4JrSMjLGbae6WlkMLVUEhUFzh4="

[mod."github.com/segmentio/ksuid"]
version = "v1.0.2"
hash = "sha256-U5qALEwLwGqqC4XwJOHtAA+1AhV1yZqFPS0z/o1KSWI="

[mod."github.com/stretchr/testify"]
version = "v1.8.0"
hash = "sha256-LDxBAebK+A06y4vbH7cd1sVBOameIY81Xm8/9OPZh7o="

[mod."github.com/x448/float16"]
version = "v0.8.4"
hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="

[mod."github.com/yuin/goldmark"]
version = "v1.4.13"
hash = "sha256-GVwFKZY6moIS6I0ZGuio/WtDif+lkZRfqWS6b4AAJyI="

[mod."github.com/zeebo/xxh3"]
version = "v1.0.2"
hash = "sha256-XXUApJ54WZeV4YBaDHNF3kLdK16nPDOZNP1Fnx1JjpI="

[mod."go.opentelemetry.io/otel"]
version = "v0.16.0"
hash = "sha256-SFXPRsIFR7l1JZVFFvalSUkhwVU+OmZFyruMcPreqhc="

[mod."go.uber.org/atomic"]
version = "v1.7.0"
hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="

[mod."go.uber.org/multierr"]
version = "v1.8.0"
hash = "sha256-WHWgw6hLI4tPKEqJt+WC38yt64OGCXfkUJDem6mM+Mw="

[mod."go.uber.org/zap"]
version = "v1.23.0"
hash = "sha256-A/Wf2F9yc+OTyX86QjTtzemUOaFSd7ptoNFaqr2smig="

[mod."golang.org/x/exp"]
version = "v0.0.0-20220916125017-b168a2c6b86b"
hash = "sha256-wIoUisHbBvzmS35jk7hw/P4DMxZpitjKFuFSXLXksks="

[mod."golang.org/x/mod"]
version = "v0.6.0-dev.0.20220419223038-86c51ed26bb4"
hash = "sha256-HS5GtzK6mLkQ/FM+GWoX4wSW0XllHK/2O3Y7O2/sFBk="

[mod."golang.org/x/net"]
version = "v0.7.0"
hash = "sha256-LgZYZRwtMqm+soNh+esxDSeRuIDxRGb9OEfYaFJHCDI="

[mod."golang.org/x/sync"]
version = "v0.0.0-20220819030929-7fc1605a5dde"
hash = "sha256-5EOxO8FRdaLW9v/DhwBmWiT2G34A2ofxSCaC7ovvpb0="

[mod."golang.org/x/sys"]
version = "v0.5.0"
hash = "sha256-0LTr3KeJ1OMQAwYUQo1513dXJtQAJn5Dq8sFkc8ps1U="

[mod."golang.org/x/term"]
version = "v0.5.0"
hash = "sha256-f3DiX7NkDsEZpPS+PbmnOH9F5WHFZ1sQrfFg/T2UPno="

[mod."golang.org/x/text"]
version = "v0.7.0"
hash = "sha256-ydgUqX+t5Qke16C6d3FP/06U/N1n+rUKpLRFj4KXjwk="

[mod."golang.org/x/tools"]
version = "v0.1.12"
hash = "sha256-D0kGneGMt+LFbdUDo9Axd0yB0a5t3Z0YKVAnJDDaBo8="

[mod."golang.org/x/xerrors"]
version = "v0.0.0-20220609144429-65e65417b02f"
hash = "sha256-tl8pv3oddbz2+KoIp7PFDKsxjQF8ocjPF8XPsY3sw38="

[mod."google.golang.org/genproto"]
version = "v0.0.0-20200825200019-8632dd797987"
hash = "sha256-dIoqnFN19QceAo1cRS9hjVKlp/VqAO+JrMv4nWdBn+M="

[mod."google.golang.org/grpc"]
version = "v1.49.0"
hash = "sha256-x4+/XjxI2HY8fZYMiEV7Kv+2SrnlmaTJX3tBl+dPUoI="

[mod."google.golang.org/protobuf"]
version = "v1.28.1"
hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="

[mod."gopkg.in/natefinch/lumberjack.v2"]
version = "v2.0.0"
hash = "sha256-CLir3wRkgNy7tXQWODk7u3RP/W7qIsO2LADdM6/vWtQ="

[mod."gopkg.in/yaml.v3"]
version = "v3.0.1"
hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
