# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  broker = {
    pname = "broker";
    version = "69d9eae560a37af18425879eaf1a7c3d59e3926c";
    src = fetchFromGitHub {
      owner = "zeek";
      repo = "broker";
      rev = "69d9eae560a37af18425879eaf1a7c3d59e3926c";
      fetchSubmodules = true;
      sha256 = "sha256-xs/uU/uD60SMv/C7cbu+jnVmSBioKhnxZK83Cl8uIJA=";
    };
    date = "2023-11-16";
  };
  caretaker = {
    pname = "caretaker";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "grego";
      repo = "caretaker";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-xP3AfwD9Er0TolAN65NfC2GkC1KlpcyV1J68KjBBEwU=";
    };
  };
  chatgpt-next-web = {
    pname = "chatgpt-next-web";
    version = "b21931c667abf2825eca43d59f794471420c1db0";
    src = fetchFromGitHub {
      owner = "Yidadaa";
      repo = "ChatGPT-Next-Web";
      rev = "b21931c667abf2825eca43d59f794471420c1db0";
      fetchSubmodules = false;
      sha256 = "sha256-KbkcZzdYfyrnD/o2XUOEQne1Wt62UAqR3P/keXxjBSc=";
    };
    date = "2023-11-24";
  };
  chatgpt-web = {
    pname = "chatgpt-web";
    version = "ed1e41c4f129cf14cc91f2ae688657a7cd3b4088";
    src = fetchFromGitHub {
      owner = "Chanzhaoyu";
      repo = "chatgpt-web";
      rev = "ed1e41c4f129cf14cc91f2ae688657a7cd3b4088";
      fetchSubmodules = false;
      sha256 = "sha256-RsQAqWXRh+DrJUxQTJ7SkOt7pWcgKZFBac7BuSeHsAw=";
    };
    date = "2023-11-23";
  };
  firecracker-task-driver = {
    pname = "firecracker-task-driver";
    version = "dbfdebbfff78794006eed9736a27b49c34278508";
    src = fetchFromGitHub {
      owner = "cneira";
      repo = "firecracker-task-driver";
      rev = "dbfdebbfff78794006eed9736a27b49c34278508";
      fetchSubmodules = false;
      sha256 = "sha256-gMaMZHEXnyx9DlkOx4pZ93UhANisRXDxGhKCV9HndHU=";
    };
    date = "2022-10-06";
  };
  gptcommit = {
    pname = "gptcommit";
    version = "v0.5.14";
    src = fetchFromGitHub {
      owner = "zurawiki";
      repo = "gptcommit";
      rev = "v0.5.14";
      fetchSubmodules = false;
      sha256 = "sha256-xjaFr1y2Fd7IWbJlegnIsfS5/oMJYd6QTnwp7IK17xM=";
    };
  };
  koodo-reader = {
    pname = "koodo-reader";
    version = "587e4bc5d8ce162d3ab03e8e6287501b0dfcb9b5";
    src = fetchFromGitHub {
      owner = "troyeguo";
      repo = "koodo-reader";
      rev = "587e4bc5d8ce162d3ab03e8e6287501b0dfcb9b5";
      fetchSubmodules = false;
      sha256 = "sha256-rG+FjI+X34IrPL45lUyVMZhtVGKTt1q5zqngvD7FG28=";
    };
    date = "2023-11-05";
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.19.0pre20231120_6832d18";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.19.0pre20231120_6832d18/install";
      sha256 = "sha256-8MP8Yu9TbGHzViDhP/Zc+ycsJAeKxCllqrpc8bY1SD8=";
    };
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  sslproxy = {
    pname = "sslproxy";
    version = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
    src = fetchFromGitHub {
      owner = "sonertari";
      repo = "SSLproxy";
      rev = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
      fetchSubmodules = false;
      sha256 = "sha256-aUU21Blcn5mT40O090BybN2nnxnCLLayKFY0PC+tHmw=";
    };
    date = "2022-12-26";
  };
  tuc = {
    pname = "tuc";
    version = "89ef29696a62357e33fa57c4bb33a9401d12c259";
    src = fetchFromGitHub {
      owner = "riquito";
      repo = "tuc";
      rev = "89ef29696a62357e33fa57c4bb33a9401d12c259";
      fetchSubmodules = false;
      sha256 = "sha256-VNp5tcZGsBltEPMbynep65uoZR/QqCGYoML8WrC8S7c=";
    };
    date = "2023-08-01";
  };
  watchexec-simple = {
    pname = "watchexec-simple";
    version = "68eee93f60cf574403b1fc97b73e42cf8e6d92e9";
    src = fetchFromGitHub {
      owner = "kurtbuilds";
      repo = "watchexec-simple";
      rev = "68eee93f60cf574403b1fc97b73e42cf8e6d92e9";
      fetchSubmodules = false;
      sha256 = "sha256-lvC79sFODEfKeZ7bTMrQIUpWQ/zFw9JyLz2lymmdQ0M=";
    };
    date = "2023-10-24";
  };
  yakgpt = {
    pname = "yakgpt";
    version = "7675e969071c3e75a641c1ea42c933cd13215cb2";
    src = fetchFromGitHub {
      owner = "yakGPT";
      repo = "yakGPT";
      rev = "7675e969071c3e75a641c1ea42c933cd13215cb2";
      fetchSubmodules = false;
      sha256 = "sha256-nA03lQ5wpa7E5hH3deYTgAv2aD7SbW2sjuZg6KWtN0w=";
    };
    date = "2023-04-25";
  };
  zeek-language-server = {
    pname = "zeek-language-server";
    version = "3b701bafd6bf3aba3deb6944254b431ca488a896";
    src = fetchFromGitHub {
      owner = "bbannier";
      repo = "zeek-language-server";
      rev = "3b701bafd6bf3aba3deb6944254b431ca488a896";
      fetchSubmodules = true;
      sha256 = "sha256-wndfy8gPvokWTKdntcduAypZbjKHhvJLv2o//EtVLQk=";
    };
    date = "2023-11-21";
  };
}
