# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  container-structure-test = {
    pname = "container-structure-test";
    version = "be4664be19d5968386a2801fe61d80ddffe29d46";
    src = fetchFromGitHub ({
      owner = "GoogleContainerTools";
      repo = "container-structure-test";
      rev = "be4664be19d5968386a2801fe61d80ddffe29d46";
      fetchSubmodules = false;
      sha256 = "sha256-jUus2BRijt5pMlrHuRlZr54XgarT4k4OGUMWi4kUxpc=";
    });
    date = "2023-03-15";
  };
  ghq = {
    pname = "ghq";
    version = "67a22bf1f7ce997082fbea36ec0ca98f0d60b3fb";
    src = fetchFromGitHub ({
      owner = "x-motemen";
      repo = "ghq";
      rev = "67a22bf1f7ce997082fbea36ec0ca98f0d60b3fb";
      fetchSubmodules = false;
      sha256 = "sha256-uUhYqfVj35/Y/Jj0t4hiAT8uknS2Tal+wvnLYTag4i0=";
    });
    date = "2023-02-23";
  };
  go-chatgpt-web = {
    pname = "go-chatgpt-web";
    version = "f77c2b2a63f16b130c6d394b5a4465db6cb21fd3";
    src = fetchFromGitHub ({
      owner = "869413421";
      repo = "chatgpt-web";
      rev = "f77c2b2a63f16b130c6d394b5a4465db6cb21fd3";
      fetchSubmodules = false;
      sha256 = "sha256-G9O2d14zj6FnMQUP9FTdGsraYWFrTSxEj0H/GSkJ1y4=";
    });
    date = "2023-03-14";
  };
  go-nfsd = {
    pname = "go-nfsd";
    version = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
    src = fetchFromGitHub ({
      owner = "mit-pdos";
      repo = "go-nfsd";
      rev = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
      fetchSubmodules = false;
      sha256 = "sha256-+bcRGlJhQSWPLVgSmAbP0Kh6mqCgmnZZksmQV7cVG3g=";
    });
    date = "2022-05-12";
  };
  gst = {
    pname = "gst";
    version = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
    src = fetchFromGitHub ({
      owner = "uetchy";
      repo = "gst";
      rev = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
      fetchSubmodules = false;
      sha256 = "sha256-NhbGHTYucfqCloVirkaDlAtQfhWP2cw4I+t/ysvvkR0=";
    });
    date = "2021-10-27";
  };
  nvdtools = {
    pname = "nvdtools";
    version = "c0d18738cde5864576f073af99669edc92e87fb4";
    src = fetchFromGitHub ({
      owner = "facebookincubator";
      repo = "nvdtools";
      rev = "c0d18738cde5864576f073af99669edc92e87fb4";
      fetchSubmodules = false;
      sha256 = "sha256-NNI1IGuj6IBPgjAfMedRDZECNnzc7B2Sem6Z6kh++Uc=";
    });
    date = "2023-02-14";
  };
  tc-redirect-tap = {
    pname = "tc-redirect-tap";
    version = "70412ed40429a56722183d1785e716765922f25a";
    src = fetchFromGitHub ({
      owner = "awslabs";
      repo = "tc-redirect-tap";
      rev = "70412ed40429a56722183d1785e716765922f25a";
      fetchSubmodules = false;
      sha256 = "sha256-l8+kj5W2bVF1+oPg2+1J2PeUx43waDgm/cS67XS4qn0=";
    });
    date = "2023-02-28";
  };
  zed = {
    pname = "zed";
    version = "de1134da86e66809e556fc2a218a21b37344a374";
    src = fetchFromGitHub ({
      owner = "brimdata";
      repo = "zed";
      rev = "de1134da86e66809e556fc2a218a21b37344a374";
      fetchSubmodules = false;
      sha256 = "sha256-2ISz428UDQeoh+2xnXr5LCnj/9mIApcJ3J90sgyP//o=";
    });
    date = "2023-03-14";
  };
  zitadel-bin = {
    pname = "zitadel-bin";
    version = "v2.21.2";
    src = fetchurl {
      url = "https://github.com/zitadel/zitadel/releases/download/v2.21.2/zitadel_Linux_x86_64.tar.gz";
      sha256 = "sha256-NvvIWgBh42ZNnI1VQ0xhJ0e3PLthdHJRyilyzyCYmXM=";
    };
  };
}
