[zitadel-bin]
src.github = "zitadel/zitadel"
fetch.url = "https://github.com/zitadel/zitadel/releases/download/$ver/zitadel-linux-amd64.tar.gz"

# [deepsea]
# src.manual= "b48e9302d079ed9f53a9123a805096a845d2c6a5"
# fetch.github = "dsnezhkov/deepsea:b48e9302d079ed9f53a9123a805096a845d2c6a5"
[go-nfsd]
src.git = "https://github.com/mit-pdos/go-nfsd"
fetch.github = "mit-pdos/go-nfsd"

[nvdtools]
src.git = "https://github.com/facebookincubator/nvdtools"
fetch.github = "facebookincubator/nvdtools"

[container-structure-test]
src.git = "https://github.com/GoogleContainerTools/container-structure-test"
fetch.github = "GoogleContainerTools/container-structure-test"

[tc-redirect-tap]
src.git = "https://github.com/awslabs/tc-redirect-tap"
fetch.github = "awslabs/tc-redirect-tap"
