[copilot-gpt4-service]
src.git = "https://github.com/aaamoon/copilot-gpt4-service"
fetch.github = "aaamoon/copilot-gpt4-service"

[chatgpt-next-web]
src.git = "https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web"
fetch.github = "ChatGPTNextWeb/ChatGPT-Next-Web"

[firecracker-task-driver]
src.git = "https://github.com/cneira/firecracker-task-driver"
fetch.github = "cneira/firecracker-task-driver"

[osquery]
#src.github = "osquery/osquery"
src.manual = "5.2.2"
fetch.url = "https://github.com/osquery/osquery/releases/download/$ver/osquery_$ver-1.linux_amd64.deb"
src.prefix = "v"

[nix-unstable-installer]
src.github = "numtide/nix-unstable-installer"
fetch.url = "https://github.com/numtide/nix-unstable-installer/releases/download/$ver/install"
src.prefix = "v"

# [koodo-reader-appimage]
# src.github = "troyeguo/koodo-reader"
# fetch.url = "https://github.com/troyeguo/koodo-reader/releases/download/v$ver/Koodo-Reader-$ver.AppImage"
# src.prefix = "v"
[koodo-reader]
src.git = "https://github.com/troyeguo/koodo-reader"
fetch.github = "troyeguo/koodo-reader"

[caretaker]
src.github = "grego/caretaker"
fetch.github = "grego/caretaker"

# Pull the contents of `Cargo.lock` into generated nix expr
# cargo_locks = ["Cargo.lock"]
[watchexec-simple]
src.git = "https://github.com/kurtbuilds/watchexec-simple"
fetch.github = "kurtbuilds/watchexec-simple"

[zeek-language-server]
src.git = "https://github.com/bbannier/zeek-language-server"
fetch.github = "bbannier/zeek-language-server"
git.fetchSubmodules = true

[sslproxy]
src.git = "https://github.com/sonertari/SSLproxy"
fetch.github = "sonertari/SSLproxy"

[yakgpt]
src.git = "https://github.com/yakGPT/yakGPT"
fetch.github = "yakGPT/yakGPT"
# [ilograph-dmg]
# src.manual = "1.5.3"
# fetch.url = "https://www.ilograph.com/desktop/release/Ilograph%20Desktop-$ver-arm64.dmg"
