# nvfetcher.toml
[vailyn]
src.github = "VainlyStrain/Vailyn"
fetch.github = "VainlyStrain/Vailyn"

[polars]
src.github = "pola-rs/polars"
fetch.github = "pola-rs/polars"

[sybilhunter]
src.git = "https://github.com/NullHypothesis/sybilhunter"
fetch.github = "NullHypothesis/sybilhunter"

[eZeeKonfigurator]
src.git = "https://github.com/esnet/eZeeKonfigurator"
fetch.github = "esnet/eZeeKonfigurator"

[eZeeKonfigurator_client]
src.git = "https://github.com/esnet/eZeeKonfigurator_client"
fetch.github = "esnet/eZeeKonfigurator_client"

[elastalert2]
src.git = "https://github.com/jertel/elastalert2"
fetch.github = "jertel/elastalert2"

[choochoo]
src.git = "https://github.com/andrewcooke/choochoo"
fetch.github = "andrewcooke/choochoo"

#################
# Python fastai #
#################
[vault-cli]
src.git = "https://github.com/peopledoc/vault-cli"
fetch.github = "peopledoc/vault-cli"

[cliche]
src.git = "https://github.com/kootenpv/cliche"
fetch.github = "kootenpv/cliche"

#Python Packages
[durationpy]
src.pypi = "durationpy"
fetch.pypi = "durationpy"

[sh]
src.pypi = "sh"
fetch.pypi = "sh"
