# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  brim = {
    pname = "brim";
    version = "0.29.0";
    src = fetchurl {
      url = "https://github.com/brimdata/brim/releases/download/v0.29.0/Brim-0.29.0.deb";
      sha256 = "sha256-cPjNZgzz9SyVr2NO3ZV0NfiO0i/jxHr5v4fAkTnz5CM=";
    };
  };
  broker = {
    pname = "broker";
    version = "2b9fe9a5128ea16ebf5a7e2753147ab517f053ac";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "broker";
      rev = "2b9fe9a5128ea16ebf5a7e2753147ab517f053ac";
      fetchSubmodules = true;
      sha256 = "sha256-+ORD7oe2tcAcyi3l+J8FXjsv0gLa1qdol9YStU0kQfk=";
    });
  };
  broker-to-json = {
    pname = "broker-to-json";
    version = "v_02";
    src = fetchFromGitHub ({
      owner = "grigorescu";
      repo = "broker-to-json";
      rev = "v_02";
      fetchSubmodules = false;
      sha256 = "sha256-SROcIR2P5ixk4yDVwkUJczdbuU4STpmTyLNBCj6dEtg=";
    });
  };
  btest = {
    pname = "btest";
    version = "0.71";
    src = fetchurl {
      url = "https://pypi.io/packages/source/b/btest/btest-0.71.tar.gz";
      sha256 = "sha256-17JpGNgq917qNp1snF2I6teeid9RxCaM6nSYiQh9Ocw=";
    };
  };
  choochoo = {
    pname = "choochoo";
    version = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
    src = fetchFromGitHub ({
      owner = "andrewcooke";
      repo = "choochoo";
      rev = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
      fetchSubmodules = false;
      sha256 = "sha256-/PjfY1thoILxpu3/PTmFRfzR4eFgraLbTXpVM54GXJk=";
    });
  };
  cliche = {
    pname = "cliche";
    version = "176a120bd90c5359e3dd6086da2807f7234925df";
    src = fetchFromGitHub ({
      owner = "kootenpv";
      repo = "cliche";
      rev = "176a120bd90c5359e3dd6086da2807f7234925df";
      fetchSubmodules = false;
      sha256 = "sha256-5SOhiqZUX8yVMx7BgnXre93XbPhZTeKdMmAq8GRNN2g=";
    });
  };
  container-structure-test = {
    pname = "container-structure-test";
    version = "59c5221e5a4e7e2c8680c273c25cb405d8f8eb8b";
    src = fetchFromGitHub ({
      owner = "GoogleContainerTools";
      repo = "container-structure-test";
      rev = "59c5221e5a4e7e2c8680c273c25cb405d8f8eb8b";
      fetchSubmodules = false;
      sha256 = "sha256-+7GuTV6a3a+fG4Kqwcq4Ro4MPCeWb0PvY3mFbsCklVc=";
    });
  };
  durationpy = {
    pname = "durationpy";
    version = "0.5";
    src = fetchurl {
      url = "https://pypi.io/packages/source/d/durationpy/durationpy-0.5.tar.gz";
      sha256 = "sha256-XvlBa1J7UNci80ZVvs+3Xkkijrgvh7hV7RkRszFLVAg=";
    };
  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "523af9490b1f403dfabad42c6b8b2800483fd6a3";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator";
      rev = "523af9490b1f403dfabad42c6b8b2800483fd6a3";
      fetchSubmodules = false;
      sha256 = "sha256-bLQPzxH9yIzZEO9W7tnxEsxYb6c1QwhyXdY1urQLnHA=";
    });
  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      sha256 = "sha256-b2QqmduoyohAIOJnZP/Vnt9FdmoOebDfmaTs5SNVoAg=";
    });
  };
  elastalert2 = {
    pname = "elastalert2";
    version = "4c0afcb7f3e08be4b47889f1f83e2dd4e7eaa514";
    src = fetchFromGitHub ({
      owner = "jertel";
      repo = "elastalert2";
      rev = "4c0afcb7f3e08be4b47889f1f83e2dd4e7eaa514";
      fetchSubmodules = false;
      sha256 = "sha256-UvyqQ9GhZoRmXfRXCzlh9IdomE7Ziqpi1LZ0ECbQ8JY=";
    });
  };
  fastai = {
    pname = "fastai";
    version = "6d5fbd849c9cafacd4588d841eccd27284c482f7";
    src = fetchFromGitHub ({
      owner = "fastai";
      repo = "fastai";
      rev = "6d5fbd849c9cafacd4588d841eccd27284c482f7";
      fetchSubmodules = false;
      sha256 = "sha256-Yul6edZAXIdbJzGsOm8OpSuHESv8C95oP5gQ6+ovjJU=";
    });
  };
  fastcore = {
    pname = "fastcore";
    version = "cced1ec2b267d125cb3c49590475783f29a0343c";
    src = fetchFromGitHub ({
      owner = "fastai";
      repo = "fastcore";
      rev = "cced1ec2b267d125cb3c49590475783f29a0343c";
      fetchSubmodules = false;
      sha256 = "sha256-py3pVDIZiRvc8rGrQyPduPdSDPaU1b/m/nPrJB5ocnc=";
    });
  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/f/fastprogress/fastprogress-1.0.2.tar.gz";
      sha256 = "sha256-lga6RCUFo6RFgdY97dzlv/HfF6y9w3JS98PxvlLB0kM=";
    };
  };
  ghq = {
    pname = "ghq";
    version = "0e02db0b9a7a6773e503dd99bdabca49bfdf67af";
    src = fetchFromGitHub ({
      owner = "x-motemen";
      repo = "ghq";
      rev = "0e02db0b9a7a6773e503dd99bdabca49bfdf67af";
      fetchSubmodules = false;
      sha256 = "sha256-chpaac01Wbdp+sA38O50iGVGt6zxA2N3/NUzhsptSVs=";
    });
  };
  go-nfsd = {
    pname = "go-nfsd";
    version = "297918dc3d4c7913a0ba91841556a7f0506a1ae2";
    src = fetchFromGitHub ({
      owner = "mit-pdos";
      repo = "go-nfsd";
      rev = "297918dc3d4c7913a0ba91841556a7f0506a1ae2";
      fetchSubmodules = false;
      sha256 = "sha256-/RoFQ+EMmOQyI8vHQH40PIbhfOUHq5hJAwfzsVZqE1k=";
    });
  };
  gst = {
    pname = "gst";
    version = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
    src = fetchFromGitHub ({
      owner = "uetchy";
      repo = "gst";
      rev = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
      fetchSubmodules = false;
      sha256 = "sha256-NhbGHTYucfqCloVirkaDlAtQfhWP2cw4I+t/ysvvkR0=";
    });
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.8.0pre20220415_b135de2";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.8.0pre20220415_b135de2/install";
      sha256 = "sha256-SgIqm1IaEnNn5FNt4BnxDrxEF/nuUzsekmBAzF9ea9g=";
    };
  };
  nvdtools = {
    pname = "nvdtools";
    version = "22daa55f30c8aa6a78565cc6b4c160c41b867636";
    src = fetchFromGitHub ({
      owner = "facebookincubator";
      repo = "nvdtools";
      rev = "22daa55f30c8aa6a78565cc6b4c160c41b867636";
      fetchSubmodules = false;
      sha256 = "sha256-uB7dfqGaoP9Xx04BykscIFQ2rckaMaj93gh5mhgMqfw=";
    });
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  py-tree-sitter = {
    pname = "py-tree-sitter";
    version = "3eb2058081f204ed39a259fe7dc3df259a887567";
    src = fetchFromGitHub ({
      owner = "tree-sitter";
      repo = "py-tree-sitter";
      rev = "3eb2058081f204ed39a259fe7dc3df259a887567";
      fetchSubmodules = true;
      sha256 = "sha256-hHfitDKcuPDFoSaM8FILU1ackwv2Lml4jjlOK5TlbcQ=";
    });
  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchFromGitHub ({
      owner = "NullHypothesis";
      repo = "sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      sha256 = "sha256-vIOibQuMauVhkxgR9QaL+pbocY7xgyamMeOhtKmye70=";
    });
  };
  vailyn = {
    pname = "vailyn";
    version = "v3.3.2-1";
    src = fetchFromGitHub ({
      owner = "VainlyStrain";
      repo = "Vailyn";
      rev = "v3.3.2-1";
      fetchSubmodules = false;
      sha256 = "sha256-eHnqfL6Nt0FDyIoZ4RhwB29h3r6ctVQKAGCeZkOk5yo=";
    });
  };
  vault-cli = {
    pname = "vault-cli";
    version = "0142476bcfda52876951f49b0990ac1d85377d3a";
    src = fetchFromGitHub ({
      owner = "peopledoc";
      repo = "vault-cli";
      rev = "0142476bcfda52876951f49b0990ac1d85377d3a";
      fetchSubmodules = false;
      sha256 = "sha256-/YNBI1IknygmqKy5JMCS63AX581YY5wqE1KN75rBPH0=";
    });
  };
  zat = {
    pname = "zat";
    version = "fed88c4310cf70c8b01c9a7eb0918b8c4d117e77";
    src = fetchFromGitHub ({
      owner = "SuperCowPowers";
      repo = "zat";
      rev = "fed88c4310cf70c8b01c9a7eb0918b8c4d117e77";
      fetchSubmodules = false;
      sha256 = "sha256-8uydkQkD5M4jFCmMLNkJDdFILYLzvJuLFfbNPLNHmHE=";
    });
  };
  zed = {
    pname = "zed";
    version = "f9b51836c0279a038b909ef5ed0f2a987dfdce6d";
    src = fetchFromGitHub ({
      owner = "brimdata";
      repo = "zed";
      rev = "f9b51836c0279a038b909ef5ed0f2a987dfdce6d";
      fetchSubmodules = false;
      sha256 = "sha256-a5Nm71p1nQnrZ4DyQJ0kOX5ROaLaEni9/LkPMwDvfrE=";
    });
  };
  zeekscript = {
    pname = "zeekscript";
    version = "ef6ea8440cd79f4284d9e686ec9520cf8b8cd7c4";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeekscript";
      rev = "ef6ea8440cd79f4284d9e686ec9520cf8b8cd7c4";
      fetchSubmodules = true;
      sha256 = "sha256-ReiP4ZpNXH2XDaWmIq8uJc13M+6/qnbvGsAX2ik/kTQ=";
    });
  };
}
