# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  container-structure-test = {
    pname = "container-structure-test";
    version = "cc5bb29e518d14a89b4dd74ba2789d808d6a62d6";
    src = fetchFromGitHub {
      owner = "GoogleContainerTools";
      repo = "container-structure-test";
      rev = "cc5bb29e518d14a89b4dd74ba2789d808d6a62d6";
      fetchSubmodules = false;
      sha256 = "sha256-RaP5ylVUkWuThQalyX4bYhbB3sPvN7Kz9cO2IM/oxDs=";
    };
    date = "2023-11-21";
  };
  go-nfsd = {
    pname = "go-nfsd";
    version = "b02df67ac6264f4a71e424288c84a9aa0a62c2a8";
    src = fetchFromGitHub {
      owner = "mit-pdos";
      repo = "go-nfsd";
      rev = "b02df67ac6264f4a71e424288c84a9aa0a62c2a8";
      fetchSubmodules = false;
      sha256 = "sha256-yRovu5H4gEo+Unk4ZxImasRKhitf1SXcfOUTDkrEprw=";
    };
    date = "2023-08-30";
  };
  nvdtools = {
    pname = "nvdtools";
    version = "d14ce526f176b589e8c26156618347faf7ffd7d4";
    src = fetchFromGitHub {
      owner = "facebookincubator";
      repo = "nvdtools";
      rev = "d14ce526f176b589e8c26156618347faf7ffd7d4";
      fetchSubmodules = false;
      sha256 = "sha256-QTUyhDgOKPaoL/S85UzLuN9Vs33WrNBwpZX9H3TlX9c=";
    };
    date = "2023-10-10";
  };
  tc-redirect-tap = {
    pname = "tc-redirect-tap";
    version = "6827f7b2f5e9ec675cb7dc9bbe4b201c228d565e";
    src = fetchFromGitHub {
      owner = "awslabs";
      repo = "tc-redirect-tap";
      rev = "6827f7b2f5e9ec675cb7dc9bbe4b201c228d565e";
      fetchSubmodules = false;
      sha256 = "sha256-hMnZVFDT/ftD0+iSQqHLqz8gfTjuQv55Kr4mR2ranFI=";
    };
    date = "2023-10-29";
  };
  zitadel-bin = {
    pname = "zitadel-bin";
    version = "v2.41.6";
    src = fetchurl {
      url = "https://github.com/zitadel/zitadel/releases/download/v2.41.6/zitadel-linux-amd64.tar.gz";
      sha256 = "sha256-YYYmiYeb7XFeBtD9JTm+Z4B1Hp5FsOD4IPhQ7m2HGwo=";
    };
  };
}
