# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  broker = {
    pname = "broker";
    version = "5fb9e1ebc54d7a36fee77ef67f9cab8d84cb4654";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "broker";
      rev = "5fb9e1ebc54d7a36fee77ef67f9cab8d84cb4654";
      fetchSubmodules = true;
      sha256 = "sha256-OsHLkxmPEXSodlMY1jRy8MHzfjUMkvewAmzGGg7eB7I=";
    });
    date = "2023-04-06";
  };
  caretaker = {
    pname = "caretaker";
    version = "v0.2.4";
    src = fetchFromGitHub ({
      owner = "grego";
      repo = "caretaker";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-xP3AfwD9Er0TolAN65NfC2GkC1KlpcyV1J68KjBBEwU=";
    });
  };
  chatgpt-web = {
    pname = "chatgpt-web";
    version = "86bba7d8f3227dca1e651fb8619af3d6aed18ddd";
    src = fetchFromGitHub ({
      owner = "Chanzhaoyu";
      repo = "chatgpt-web";
      rev = "86bba7d8f3227dca1e651fb8619af3d6aed18ddd";
      fetchSubmodules = false;
      sha256 = "sha256-kk0/43lRyj78DHKiM/Kgy3cWfX40bY2CijjbiEXA0Gc=";
    });
    date = "2023-04-07";
  };
  gptcommit = {
    pname = "gptcommit";
    version = "v0.5.7";
    src = fetchFromGitHub ({
      owner = "zurawiki";
      repo = "gptcommit";
      rev = "v0.5.7";
      fetchSubmodules = false;
      sha256 = "sha256-ymG0D/geYH0o4fBzggeJH41fwZnO3THUV8ipk5GfwQc=";
    });
  };
  koodo-reader = {
    pname = "koodo-reader";
    version = "ccb8da34811584406050fcb0e03a045b04ae8262";
    src = fetchFromGitHub ({
      owner = "troyeguo";
      repo = "koodo-reader";
      rev = "ccb8da34811584406050fcb0e03a045b04ae8262";
      fetchSubmodules = false;
      sha256 = "sha256-rUEXzrN9NA2abvyWBef3Z/dHLV7W3QJwHCq0sKefgxU=";
    });
    date = "2023-03-19";
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.15.0pre20230331_cf76b38";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.15.0pre20230331_cf76b38/install";
      sha256 = "sha256-sDrOTqjylj8wtVcF60b9tQYmu/cdJhd3kHXlsFQ65YQ=";
    };
  };
  openproject = {
    pname = "openproject";
    version = "9d149024e4a088e81226e50cfd2ebe91f276da10";
    src = fetchFromGitHub ({
      owner = "opf";
      repo = "openproject";
      rev = "9d149024e4a088e81226e50cfd2ebe91f276da10";
      fetchSubmodules = false;
      sha256 = "sha256-MZUUXNMUlMHhThLUGsTrEAZ1GkHUV83+piR8YigcYhE=";
    });
    date = "2023-04-07";
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  sslproxy = {
    pname = "sslproxy";
    version = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
    src = fetchFromGitHub ({
      owner = "sonertari";
      repo = "SSLproxy";
      rev = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
      fetchSubmodules = false;
      sha256 = "sha256-aUU21Blcn5mT40O090BybN2nnxnCLLayKFY0PC+tHmw=";
    });
    date = "2022-12-26";
  };
  tuc = {
    pname = "tuc";
    version = "6c1418b02bc1fcbe2104c06365333261327b7bc4";
    src = fetchFromGitHub ({
      owner = "riquito";
      repo = "tuc";
      rev = "6c1418b02bc1fcbe2104c06365333261327b7bc4";
      fetchSubmodules = false;
      sha256 = "sha256-CUHgDD7ltvbD7hOCeeSfQfiF0T+QzYTvWvZ9w1N7oKA=";
    });
    date = "2023-04-01";
  };
  watchexec-simple = {
    pname = "watchexec-simple";
    version = "2ce685a1804d6ffed2c1c20abff2a9cf648c7188";
    src = fetchFromGitHub ({
      owner = "kurtbuilds";
      repo = "watchexec-simple";
      rev = "2ce685a1804d6ffed2c1c20abff2a9cf648c7188";
      fetchSubmodules = false;
      sha256 = "sha256-AOweMMWuJx9mtSss5Iett0fTVBoZrjCaDGnzOO8RrMw=";
    });
    date = "2022-11-24";
  };
  yakgpt = {
    pname = "yakgpt";
    version = "c43363d45cdad1d4e16892788f68a26923d95882";
    src = fetchFromGitHub ({
      owner = "yakGPT";
      repo = "yakGPT";
      rev = "c43363d45cdad1d4e16892788f68a26923d95882";
      fetchSubmodules = false;
      sha256 = "sha256-OWFYUm3oqFRhuG5WM1ckQt5jWwVB2Tv/PXPu0iGhWTQ=";
    });
    date = "2023-04-05";
  };
  zeek-language-server = {
    pname = "zeek-language-server";
    version = "6bb43669f0f789539d9aa297661300c4075434eb";
    src = fetchFromGitHub ({
      owner = "bbannier";
      repo = "zeek-language-server";
      rev = "6bb43669f0f789539d9aa297661300c4075434eb";
      fetchSubmodules = true;
      sha256 = "sha256-L/THcvH2+IJ7utvdOh+Zk+LN4+gui23v6ACPe1pT7wU=";
    });
    date = "2023-03-30";
  };
  zui = {
    pname = "zui";
    version = "1.0.1";
    src = fetchurl {
      url = "https://github.com/brimdata/zui/releases/download/v1.0.1/zui_1.0.1_amd64.deb";
      sha256 = "sha256-gdCqZqsagBOYSYsOFsxF44G+0IBaQyX/gDimddOhnlM=";
    };
  };
}
