# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  broker = {
    pname = "broker";
    version = "86ed39b80c272cff44bb95f58eeda1bc5ff6f65c";
    src = fetchFromGitHub {
      owner = "zeek";
      repo = "broker";
      rev = "86ed39b80c272cff44bb95f58eeda1bc5ff6f65c";
      fetchSubmodules = true;
      sha256 = "sha256-/rRTicBsSQR1G+wpDZigpp9+BJIgS6tRLwJjpTzXwVA=";
    };
    date = "2023-10-13";
  };
  caretaker = {
    pname = "caretaker";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "grego";
      repo = "caretaker";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-xP3AfwD9Er0TolAN65NfC2GkC1KlpcyV1J68KjBBEwU=";
    };
  };
  chatgpt-next-web = {
    pname = "chatgpt-next-web";
    version = "b90dfb48ee0446fdcb567dae2b77220508f62f0d";
    src = fetchFromGitHub {
      owner = "Yidadaa";
      repo = "ChatGPT-Next-Web";
      rev = "b90dfb48ee0446fdcb567dae2b77220508f62f0d";
      fetchSubmodules = false;
      sha256 = "sha256-Hm5RFETFBtsqYrUXsymUuPWgQGIgalepAKS8iG20otE=";
    };
    date = "2023-10-26";
  };
  chatgpt-web = {
    pname = "chatgpt-web";
    version = "a6605e8a57750903f2a720ead630e25368667309";
    src = fetchFromGitHub {
      owner = "Chanzhaoyu";
      repo = "chatgpt-web";
      rev = "a6605e8a57750903f2a720ead630e25368667309";
      fetchSubmodules = false;
      sha256 = "sha256-zueRv9ztYbyrV1L0QbUFr9dtneGeWCH7v8CfNknFaeA=";
    };
    date = "2023-10-11";
  };
  firecracker-task-driver = {
    pname = "firecracker-task-driver";
    version = "dbfdebbfff78794006eed9736a27b49c34278508";
    src = fetchFromGitHub {
      owner = "cneira";
      repo = "firecracker-task-driver";
      rev = "dbfdebbfff78794006eed9736a27b49c34278508";
      fetchSubmodules = false;
      sha256 = "sha256-gMaMZHEXnyx9DlkOx4pZ93UhANisRXDxGhKCV9HndHU=";
    };
    date = "2022-10-06";
  };
  gptcommit = {
    pname = "gptcommit";
    version = "v0.5.14";
    src = fetchFromGitHub {
      owner = "zurawiki";
      repo = "gptcommit";
      rev = "v0.5.14";
      fetchSubmodules = false;
      sha256 = "sha256-xjaFr1y2Fd7IWbJlegnIsfS5/oMJYd6QTnwp7IK17xM=";
    };
  };
  koodo-reader = {
    pname = "koodo-reader";
    version = "0a99508155e45fcb60df0f2a8b3c69195c3cd3ec";
    src = fetchFromGitHub {
      owner = "troyeguo";
      repo = "koodo-reader";
      rev = "0a99508155e45fcb60df0f2a8b3c69195c3cd3ec";
      fetchSubmodules = false;
      sha256 = "sha256-8n2311CrMH7Q2+Tm6MlVO39i83cFItKHWYFj6K9SGao=";
    };
    date = "2023-10-30";
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.19.0pre20231026_1dc6a65";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.19.0pre20231026_1dc6a65/install";
      sha256 = "sha256-LR46TTKHcUEVJNLudd1a97zmtBsMG7VNQ776WJOivKU=";
    };
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  sslproxy = {
    pname = "sslproxy";
    version = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
    src = fetchFromGitHub {
      owner = "sonertari";
      repo = "SSLproxy";
      rev = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
      fetchSubmodules = false;
      sha256 = "sha256-aUU21Blcn5mT40O090BybN2nnxnCLLayKFY0PC+tHmw=";
    };
    date = "2022-12-26";
  };
  tuc = {
    pname = "tuc";
    version = "89ef29696a62357e33fa57c4bb33a9401d12c259";
    src = fetchFromGitHub {
      owner = "riquito";
      repo = "tuc";
      rev = "89ef29696a62357e33fa57c4bb33a9401d12c259";
      fetchSubmodules = false;
      sha256 = "sha256-VNp5tcZGsBltEPMbynep65uoZR/QqCGYoML8WrC8S7c=";
    };
    date = "2023-08-01";
  };
  watchexec-simple = {
    pname = "watchexec-simple";
    version = "68eee93f60cf574403b1fc97b73e42cf8e6d92e9";
    src = fetchFromGitHub {
      owner = "kurtbuilds";
      repo = "watchexec-simple";
      rev = "68eee93f60cf574403b1fc97b73e42cf8e6d92e9";
      fetchSubmodules = false;
      sha256 = "sha256-lvC79sFODEfKeZ7bTMrQIUpWQ/zFw9JyLz2lymmdQ0M=";
    };
    date = "2023-10-24";
  };
  yakgpt = {
    pname = "yakgpt";
    version = "7675e969071c3e75a641c1ea42c933cd13215cb2";
    src = fetchFromGitHub {
      owner = "yakGPT";
      repo = "yakGPT";
      rev = "7675e969071c3e75a641c1ea42c933cd13215cb2";
      fetchSubmodules = false;
      sha256 = "sha256-nA03lQ5wpa7E5hH3deYTgAv2aD7SbW2sjuZg6KWtN0w=";
    };
    date = "2023-04-25";
  };
  zeek-language-server = {
    pname = "zeek-language-server";
    version = "e9e28406875b6c04fe07643c2b045842a6cc4be1";
    src = fetchFromGitHub {
      owner = "bbannier";
      repo = "zeek-language-server";
      rev = "e9e28406875b6c04fe07643c2b045842a6cc4be1";
      fetchSubmodules = true;
      sha256 = "sha256-KpFVz9IP7Xl2w/2ZILWHwNjIUgPF4eXKpSai8fy5xW8=";
    };
    date = "2023-10-30";
  };
}
