# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  tc-redirect-tap = {
    pname = "tc-redirect-tap";
    version = "c02cef088b3b7f8d2c65271aace7b3de076294e3";
    src = fetchFromGitHub {
      owner = "awslabs";
      repo = "tc-redirect-tap";
      rev = "c02cef088b3b7f8d2c65271aace7b3de076294e3";
      fetchSubmodules = false;
      sha256 = "sha256-sGYxO/LxkyazANOdBLEsCLb5y/9K8PNAWkmxGKWa6CE=";
    };
  };
}
