# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  caretaker = {
    pname = "caretaker";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "grego";
      repo = "caretaker";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-xP3AfwD9Er0TolAN65NfC2GkC1KlpcyV1J68KjBBEwU=";
    };
  };
  chatgpt-next-web = {
    pname = "chatgpt-next-web";
    version = "bb26c03141473c9437827ceb559d43041b149604";
    src = fetchFromGitHub {
      owner = "ChatGPTNextWeb";
      repo = "ChatGPT-Next-Web";
      rev = "bb26c03141473c9437827ceb559d43041b149604";
      fetchSubmodules = false;
      sha256 = "sha256-630TbrrOD92APeUpnhhHVOWCLIrJtDAYQxeGdrRrSdE=";
    };
    date = "2024-02-05";
  };
  firecracker-task-driver = {
    pname = "firecracker-task-driver";
    version = "dbfdebbfff78794006eed9736a27b49c34278508";
    src = fetchFromGitHub {
      owner = "cneira";
      repo = "firecracker-task-driver";
      rev = "dbfdebbfff78794006eed9736a27b49c34278508";
      fetchSubmodules = false;
      sha256 = "sha256-gMaMZHEXnyx9DlkOx4pZ93UhANisRXDxGhKCV9HndHU=";
    };
    date = "2022-10-06";
  };
  koodo-reader = {
    pname = "koodo-reader";
    version = "3aafbeb3cf4eefe8b4ace1cdfbd84f2e536b1600";
    src = fetchFromGitHub {
      owner = "troyeguo";
      repo = "koodo-reader";
      rev = "3aafbeb3cf4eefe8b4ace1cdfbd84f2e536b1600";
      fetchSubmodules = false;
      sha256 = "sha256-Tpy4N+Z/UFKV4iT+yU2aqr81pLIjAwVDQldGIEVfaWA=";
    };
    date = "2024-01-30";
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.20.0pre20240123_08bf284";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.20.0pre20240123_08bf284/install";
      sha256 = "sha256-iAThBSX263Bx8222qaAmVrgn9z9IEjregWNTPorCwGA=";
    };
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  sslproxy = {
    pname = "sslproxy";
    version = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
    src = fetchFromGitHub {
      owner = "sonertari";
      repo = "SSLproxy";
      rev = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
      fetchSubmodules = false;
      sha256 = "sha256-aUU21Blcn5mT40O090BybN2nnxnCLLayKFY0PC+tHmw=";
    };
    date = "2022-12-26";
  };
  watchexec-simple = {
    pname = "watchexec-simple";
    version = "68eee93f60cf574403b1fc97b73e42cf8e6d92e9";
    src = fetchFromGitHub {
      owner = "kurtbuilds";
      repo = "watchexec-simple";
      rev = "68eee93f60cf574403b1fc97b73e42cf8e6d92e9";
      fetchSubmodules = false;
      sha256 = "sha256-lvC79sFODEfKeZ7bTMrQIUpWQ/zFw9JyLz2lymmdQ0M=";
    };
    date = "2023-10-24";
  };
  yakgpt = {
    pname = "yakgpt";
    version = "9da0bd57b5fac964b526f9b5eee86ecb2ba7023a";
    src = fetchFromGitHub {
      owner = "yakGPT";
      repo = "yakGPT";
      rev = "9da0bd57b5fac964b526f9b5eee86ecb2ba7023a";
      fetchSubmodules = false;
      sha256 = "sha256-gA64Lc5fIhrxHSvX2ArJyylxppcHprqIe0aTZCBB4r4=";
    };
    date = "2024-02-05";
  };
  zeek-language-server = {
    pname = "zeek-language-server";
    version = "b691b42febcebf320ee1a0e5e2b471f2bc51be0d";
    src = fetchFromGitHub {
      owner = "bbannier";
      repo = "zeek-language-server";
      rev = "b691b42febcebf320ee1a0e5e2b471f2bc51be0d";
      fetchSubmodules = true;
      sha256 = "sha256-TxMMC0Ygn6GzZkRJJwUcLh4/3C4X9eZBTa/go9hUoX4=";
    };
    date = "2024-02-05";
  };
}
