# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  container-structure-test = {
    pname = "container-structure-test";
    version = "3e6fe0f52eeebfe9cd2962b27d40cc2927fe30ec";
    src = fetchFromGitHub ({
      owner = "GoogleContainerTools";
      repo = "container-structure-test";
      rev = "3e6fe0f52eeebfe9cd2962b27d40cc2927fe30ec";
      fetchSubmodules = false;
      sha256 = "sha256-hMbBPNbrAlDt401rZqIg1t+3p3DYSI6JeeZ3bQI1z1E=";
    });
    date = "2022-08-31";
  };
  ghq = {
    pname = "ghq";
    version = "8f948f2d8b69cd346afc6331f58e673230df5b5e";
    src = fetchFromGitHub ({
      owner = "x-motemen";
      repo = "ghq";
      rev = "8f948f2d8b69cd346afc6331f58e673230df5b5e";
      fetchSubmodules = false;
      sha256 = "sha256-jxqTM4nn5PpIDkCttRI6WzJ5eAhuM8Z2fIBsO6IJ2YA=";
    });
    date = "2022-05-08";
  };
  go-nfsd = {
    pname = "go-nfsd";
    version = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
    src = fetchFromGitHub ({
      owner = "mit-pdos";
      repo = "go-nfsd";
      rev = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
      fetchSubmodules = false;
      sha256 = "sha256-+bcRGlJhQSWPLVgSmAbP0Kh6mqCgmnZZksmQV7cVG3g=";
    });
    date = "2022-05-12";
  };
  gst = {
    pname = "gst";
    version = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
    src = fetchFromGitHub ({
      owner = "uetchy";
      repo = "gst";
      rev = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
      fetchSubmodules = false;
      sha256 = "sha256-NhbGHTYucfqCloVirkaDlAtQfhWP2cw4I+t/ysvvkR0=";
    });
    date = "2021-10-27";
  };
  nvdtools = {
    pname = "nvdtools";
    version = "7280ba547acb31be077423560a89b453acae07d4";
    src = fetchFromGitHub ({
      owner = "facebookincubator";
      repo = "nvdtools";
      rev = "7280ba547acb31be077423560a89b453acae07d4";
      fetchSubmodules = false;
      sha256 = "sha256-hX20yeHA8wZyrChHD1RH2Qtz+46hirVVbo8n3IIh//A=";
    });
    date = "2022-10-10";
  };
  tc-redirect-tap = {
    pname = "tc-redirect-tap";
    version = "9f2f6be89079d4f3ffc179138cbff36542669809";
    src = fetchFromGitHub ({
      owner = "awslabs";
      repo = "tc-redirect-tap";
      rev = "9f2f6be89079d4f3ffc179138cbff36542669809";
      fetchSubmodules = false;
      sha256 = "sha256-OuacH5SPt0whVbcvmzlRhExcOERBFSfAy/49T2Unw+A=";
    });
    date = "2022-10-04";
  };
  zed = {
    pname = "zed";
    version = "c7564408f866550c192d0a14c8d770f942f060e1";
    src = fetchFromGitHub ({
      owner = "brimdata";
      repo = "zed";
      rev = "c7564408f866550c192d0a14c8d770f942f060e1";
      fetchSubmodules = false;
      sha256 = "sha256-mtz/Nrr9Cp6TEFGv9iSIOSXQK5QYGXQV8WntIsdBCfI=";
    });
    date = "2022-10-13";
  };
}
