# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  container-structure-test = {
    pname = "container-structure-test";
    version = "5388c503b404d1eaf910b5638549ae8bc1710470";
    src = fetchFromGitHub ({
      owner = "GoogleContainerTools";
      repo = "container-structure-test";
      rev = "5388c503b404d1eaf910b5638549ae8bc1710470";
      fetchSubmodules = false;
      sha256 = "sha256-xme0PxfqFJF2a4h9TVpWszNeZz/BTm0SVAZW0kEYwR0=";
    });
    date = "2022-11-22";
  };
  ghq = {
    pname = "ghq";
    version = "8f948f2d8b69cd346afc6331f58e673230df5b5e";
    src = fetchFromGitHub ({
      owner = "x-motemen";
      repo = "ghq";
      rev = "8f948f2d8b69cd346afc6331f58e673230df5b5e";
      fetchSubmodules = false;
      sha256 = "sha256-jxqTM4nn5PpIDkCttRI6WzJ5eAhuM8Z2fIBsO6IJ2YA=";
    });
    date = "2022-05-08";
  };
  go-nfsd = {
    pname = "go-nfsd";
    version = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
    src = fetchFromGitHub ({
      owner = "mit-pdos";
      repo = "go-nfsd";
      rev = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
      fetchSubmodules = false;
      sha256 = "sha256-+bcRGlJhQSWPLVgSmAbP0Kh6mqCgmnZZksmQV7cVG3g=";
    });
    date = "2022-05-12";
  };
  gst = {
    pname = "gst";
    version = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
    src = fetchFromGitHub ({
      owner = "uetchy";
      repo = "gst";
      rev = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
      fetchSubmodules = false;
      sha256 = "sha256-NhbGHTYucfqCloVirkaDlAtQfhWP2cw4I+t/ysvvkR0=";
    });
    date = "2021-10-27";
  };
  nvdtools = {
    pname = "nvdtools";
    version = "adaf938e36934e64dbff042b0205ee13eb381d77";
    src = fetchFromGitHub ({
      owner = "facebookincubator";
      repo = "nvdtools";
      rev = "adaf938e36934e64dbff042b0205ee13eb381d77";
      fetchSubmodules = false;
      sha256 = "sha256-9GlcjR8nBIXzYEllMc4LK9yOdI2RPCyiQXIZqexTFNw=";
    });
    date = "2022-12-14";
  };
  tc-redirect-tap = {
    pname = "tc-redirect-tap";
    version = "8dcd1aa8c7a77b4bd4f47ec0976d17d65758b447";
    src = fetchFromGitHub ({
      owner = "awslabs";
      repo = "tc-redirect-tap";
      rev = "8dcd1aa8c7a77b4bd4f47ec0976d17d65758b447";
      fetchSubmodules = false;
      sha256 = "sha256-sHyQzjthlADbFCGRtqMtHJV+PsyhaUwENlSc33EKkPo=";
    });
    date = "2022-12-02";
  };
  zed = {
    pname = "zed";
    version = "5f4c4e818d2404cb8f6f6d2b914b93d5fae4a3a0";
    src = fetchFromGitHub ({
      owner = "brimdata";
      repo = "zed";
      rev = "5f4c4e818d2404cb8f6f6d2b914b93d5fae4a3a0";
      fetchSubmodules = false;
      sha256 = "sha256-WnP1ZHWGlK5kq/KHlwRtCK7N82JvP0XVCZr/2GZtZPA=";
    });
    date = "2022-12-15";
  };
}
