schema = 3

[mod]

[mod."github.com/Azure/go-ansiterm"]
version = "v0.0.0-20210617225240-d185dfc1b5a1"
hash = "sha256-rOhb0GMLPdnh1302vaxFjO20fM69hCT29hQD1F1YpPg="

[mod."github.com/GoogleContainerTools/container-diff"]
version = "v0.14.1-0.20190219205308-3f6b025c016c"
hash = "sha256-APcjZhX8WcbodiPEg++JZLq4YMSpOwg7u4QGI6VP9MU="

[mod."github.com/Microsoft/go-winio"]
version = "v0.4.17"
hash = "sha256-yYk1RgAFwwS9kkWq8m+a1GUF906L1H9C9u2RTqaKrz4="

[mod."github.com/Microsoft/hcsshim"]
version = "v0.9.0"
hash = "sha256-R6KYTtAFozZ/zv1LZhz0fWK2NW/Mmury7WGqTN+yHFY="

[mod."github.com/containerd/containerd"]
version = "v1.5.7"
hash = "sha256-jXiey29urTb1Ltwm/QU+Tm87N0a9/0keJnpMRKlfDpc="

[mod."github.com/containerd/stargz-snapshotter/estargz"]
version = "v0.4.1"
hash = "sha256-u12sivujOnkivmilcUcJdupzulcJbw0txa2xJBCP7pI="

[mod."github.com/docker/cli"]
version = "v0.0.0-20191017083524-a8ff7f821017"
hash = "sha256-xEP3S+zFu893qmL8hxBiWdn7o5KoS23+oQdi/dhLHAA="

[mod."github.com/docker/distribution"]
version = "v2.7.1+incompatible"
hash = "sha256-8AFnEYjwqs8AzpSNBYgKmbUfFiCAxS+UH5SBFSuEctc="

[mod."github.com/docker/docker"]
version = "v20.10.8+incompatible"
hash = "sha256-FBQru/uSGUdAGdvONawzJgJArR1THHOb7u63j/oQTQ0="

[mod."github.com/docker/docker-credential-helpers"]
version = "v0.6.3"
hash = "sha256-vr9yr30M7VFpIKUr0VK37EFuBvPfPzFkPkk87WPMMZI="

[mod."github.com/docker/go-connections"]
version = "v0.4.0"
hash = "sha256-GHNIjOuuNp5lFQ308+nDNwQPGESCVV7bCUxSW5ZxZlc="

[mod."github.com/docker/go-units"]
version = "v0.4.0"
hash = "sha256-f9d4OzZqYcsgP2gqutTPRju5BVFz4/pzefgSipGSD00="

[mod."github.com/fsouza/go-dockerclient"]
version = "v1.3.6"
hash = "sha256-3h0eNPIlVxEstkAolIuJbUNt4rtMNeKxVF8ITJIz9Rc="

[mod."github.com/gogo/protobuf"]
version = "v1.3.2"
hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="

[mod."github.com/golang/protobuf"]
version = "v1.5.0"
hash = "sha256-UbjypOyvcr3GwutjMR6Y3kUYcc4F7SjhCrak2PSxRPE="

[mod."github.com/google/go-cmp"]
version = "v0.5.6"
hash = "sha256-OlzzRmcIdX45NA5h/C90NfJ/th0LB+tMHT6WzdQFK1M="

[mod."github.com/google/go-containerregistry"]
version = "v0.5.1"
hash = "sha256-DhisHAe3c/C2szC9g/QE62/0Fcp/ljLtpkllLr2MHOI="

[mod."github.com/ijc/Gotty"]
version = "v0.0.0-20170406111628-a8b993ba6abd"
hash = "sha256-JzhRLI/I6YbXXDsJyhXAGaQuIr7xT1koIEzPDRddyg0="

[mod."github.com/inconshreveable/mousetrap"]
version = "v1.0.0"
hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="

[mod."github.com/moby/sys/mount"]
version = "v0.3.0"
hash = "sha256-ic+jPKl7ReVtaJNxDn0alBfad2vmo/9ir6YoEOEfeSs="

[mod."github.com/moby/sys/mountinfo"]
version = "v0.5.0"
hash = "sha256-4SKE86a+k/4/nR4LJVCYGORBuzi7A3FN5mG/qrgwNuI="

[mod."github.com/moby/term"]
version = "v0.0.0-20210619224110-3f7ff695adc6"
hash = "sha256-ji80C4u0OJb59wIuPF4LiWf/yaGqZVfFsy+irp25Sc0="

[mod."github.com/opencontainers/go-digest"]
version = "v1.0.0"
hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="

[mod."github.com/opencontainers/image-spec"]
version = "v1.0.1"
hash = "sha256-G7VBimb9zaXD+DN20h5dL/C8Wh34OjHW3ee4marpVdQ="

[mod."github.com/opencontainers/runc"]
version = "v1.0.2"
hash = "sha256-zNccJ76NI9M2PgAAk9S5yGM1pJGrY3acFYUkBHp8ovA="

[mod."github.com/pkg/errors"]
version = "v0.9.1"
hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="

[mod."github.com/sirupsen/logrus"]
version = "v1.8.1"
hash = "sha256-vUIDlLXYBD74+JqdoSx+W3J6r5cOk63heo0ElsHizoM="

[mod."github.com/spf13/cobra"]
version = "v1.5.0"
hash = "sha256-rcyHWrxshA5DVpxrSba5X4NjppqOGrJ64QkUKKnfW2E="

[mod."github.com/spf13/pflag"]
version = "v1.0.5"
hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="

[mod."golang.org/x/crypto"]
version = "v0.0.0-20210322153248-0c34fe9e7dc2"
hash = "sha256-uGPI5kEoB7AUCUPbinTqau5WQDzaqwsZeR2wz4L+Ogg="

[mod."golang.org/x/net"]
version = "v0.0.0-20210825183410-e898025ed96a"
hash = "sha256-6JIOrrTPt20Ozo9mPE9PIMOvIYp6IytJjCXxof5ko+Q="

[mod."golang.org/x/sync"]
version = "v0.0.0-20210220032951-036812b2e83c"
hash = "sha256-qyBoAsnVWZyQM7UkJ573EjijMHK0q5mVoY/o4a8Agr4="

[mod."golang.org/x/sys"]
version = "v0.0.0-20211025201205-69cdffdb9359"
hash = "sha256-GE8ysfcBR4XoK0X9vmu6PVEQmnTCe5+GY9zUAF223L8="

[mod."golang.org/x/term"]
version = "v0.0.0-20201126162022-7de9c90e9dd1"
hash = "sha256-ykpqi1F7Yzo1BVwuG0nbQOZnK0qevcCD2xqbXbsoQq0="

[mod."google.golang.org/genproto"]
version = "v0.0.0-20201110150050-8816d57aaa9a"
hash = "sha256-qUoiblDbWa2di32srE6iOgp7CVISr+Gt28z/gXi6SiQ="

[mod."google.golang.org/grpc"]
version = "v1.40.0"
hash = "sha256-8O5svL9J3wgPuwQrCl59ZpNlmasR6bP1PO1i3QC+5mw="

[mod."google.golang.org/protobuf"]
version = "v1.26.0"
hash = "sha256-RzsCfEkChrIx/LL3SoBlsTRQ3kKbysfhG4HOujdAdLw="

[mod."gopkg.in/yaml.v2"]
version = "v2.4.0"
hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
