# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  brim = {
    pname = "brim";
    version = "0.31.0";
    src = fetchurl {
      url = "https://github.com/brimdata/brim/releases/download/v0.31.0/Brim-0.31.0.deb";
      sha256 = "sha256-ouJB8DHK5IZdPCZ9/r7ah7qaSWh5L05EHvklaBhfz1A=";
    };
  };
  broker = {
    pname = "broker";
    version = "bc0205ce1fc06ddb91abb6744cb79c7eb846c23e";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "broker";
      rev = "bc0205ce1fc06ddb91abb6744cb79c7eb846c23e";
      fetchSubmodules = true;
      sha256 = "sha256-o4VKBHiReARgkGRSSBot3lFxaq9nM9v56AQglw3G+Zc=";
    });
    date = "2023-02-01";
  };
  caretaker = {
    pname = "caretaker";
    version = "v0.2.4";
    src = fetchFromGitHub ({
      owner = "grego";
      repo = "caretaker";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-xP3AfwD9Er0TolAN65NfC2GkC1KlpcyV1J68KjBBEwU=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./caretaker-v0.2.4/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  gptcommit = {
    pname = "gptcommit";
    version = "v0.1.14";
    src = fetchFromGitHub ({
      owner = "zurawiki";
      repo = "gptcommit";
      rev = "v0.1.14";
      fetchSubmodules = false;
      sha256 = "sha256-2w7FYr43uR5O2Tr1rZutcg1cjQQwQmmSRbZvT8OfvsM=";
    });
  };
  koodo-reader = {
    pname = "koodo-reader";
    version = "2db88a59fdee9705a68242fefae4960c482a69a5";
    src = fetchFromGitHub ({
      owner = "troyeguo";
      repo = "koodo-reader";
      rev = "2db88a59fdee9705a68242fefae4960c482a69a5";
      fetchSubmodules = false;
      sha256 = "sha256-MMv7RQ3DgqvRZ0TUZfN1CGHRyNnowPldRpz3NFnAt0U=";
    });
    date = "2023-01-14";
  };
  koodo-reader-appimage = {
    pname = "koodo-reader-appimage";
    version = "1.5.1";
    src = fetchurl {
      url = "https://github.com/troyeguo/koodo-reader/releases/download/v1.5.1/Koodo-Reader-1.5.1.AppImage";
      sha256 = "sha256-fpkX6vgp7EtIyMIc4EWnpsI4mxGGDwAHO6kAco0Gi38=";
    };
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.14.0pre20230127_ccaadc9";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.14.0pre20230127_ccaadc9/install";
      sha256 = "sha256-6jLck9J1SnMNHlVlRDcKtqNh2xYWpyh85KvwhSAmGj0=";
    };
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  sslproxy = {
    pname = "sslproxy";
    version = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
    src = fetchFromGitHub ({
      owner = "sonertari";
      repo = "SSLproxy";
      rev = "30ed5b420002c8f1ac6f5c865373baa1e46bc4b8";
      fetchSubmodules = false;
      sha256 = "sha256-aUU21Blcn5mT40O090BybN2nnxnCLLayKFY0PC+tHmw=";
    });
    date = "2022-12-26";
  };
  tuc = {
    pname = "tuc";
    version = "2b73054dde91e7efb0985cca322acd7c5f1093e0";
    src = fetchFromGitHub ({
      owner = "riquito";
      repo = "tuc";
      rev = "2b73054dde91e7efb0985cca322acd7c5f1093e0";
      fetchSubmodules = false;
      sha256 = "sha256-xzBseHMejxPFqQf3dmxoFv+dfxMrLUJA762latUp9TM=";
    });
    date = "2022-10-21";
  };
  watchexec-simple = {
    pname = "watchexec-simple";
    version = "2ce685a1804d6ffed2c1c20abff2a9cf648c7188";
    src = fetchFromGitHub ({
      owner = "kurtbuilds";
      repo = "watchexec-simple";
      rev = "2ce685a1804d6ffed2c1c20abff2a9cf648c7188";
      fetchSubmodules = false;
      sha256 = "sha256-AOweMMWuJx9mtSss5Iett0fTVBoZrjCaDGnzOO8RrMw=";
    });
    date = "2022-11-24";
  };
  zeek-language-server = {
    pname = "zeek-language-server";
    version = "e64d862ddf4ec92db1d58333e00bfe01b2c9db8e";
    src = fetchFromGitHub ({
      owner = "bbannier";
      repo = "zeek-language-server";
      rev = "e64d862ddf4ec92db1d58333e00bfe01b2c9db8e";
      fetchSubmodules = true;
      sha256 = "sha256-Ttslj/bQ2Ifl+aUhC7oW37PBPW1VJbJRu89gEsprl1I=";
    });
    date = "2023-01-31";
  };
}
