# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  brim = {
    pname = "brim";
    version = "0.31.0";
    src = fetchurl {
      url = "https://github.com/brimdata/brim/releases/download/v0.31.0/Brim-0.31.0.deb";
      sha256 = "sha256-ouJB8DHK5IZdPCZ9/r7ah7qaSWh5L05EHvklaBhfz1A=";
    };
  };
  broker = {
    pname = "broker";
    version = "88bd9d55239699283162686f0d56586190b5410b";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "broker";
      rev = "88bd9d55239699283162686f0d56586190b5410b";
      fetchSubmodules = true;
      sha256 = "sha256-dGKsFXQgdglACpcR083FkBl4MSArGNKJQdOH3ejIAYU=";
    });
    date = "2022-11-29";
  };
  caretaker = {
    pname = "caretaker";
    version = "v0.2.4";
    src = fetchFromGitHub ({
      owner = "grego";
      repo = "caretaker";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-xP3AfwD9Er0TolAN65NfC2GkC1KlpcyV1J68KjBBEwU=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./caretaker-v0.2.4/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  koodo-reader-appimage = {
    pname = "koodo-reader-appimage";
    version = "1.5.1";
    src = fetchurl {
      url = "https://github.com/troyeguo/koodo-reader/releases/download/v1.5.1/Koodo-Reader-1.5.1.AppImage";
      sha256 = "sha256-fpkX6vgp7EtIyMIc4EWnpsI4mxGGDwAHO6kAco0Gi38=";
    };
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.13.0pre20221215_26c7602";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.13.0pre20221215_26c7602/install";
      sha256 = "sha256-zn52EqpdWns1rbbkrF+mxnFrq0KWlMRNNZpzsaPY9YM=";
    };
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  sslproxy = {
    pname = "sslproxy";
    version = "e456f56001e4dd99972a0430122a5782538a60fd";
    src = fetchFromGitHub ({
      owner = "sonertari";
      repo = "SSLproxy";
      rev = "e456f56001e4dd99972a0430122a5782538a60fd";
      fetchSubmodules = false;
      sha256 = "sha256-HH2QMBfX907oqdd+OlY0Wai/fOsrA5tI/BWW5Vj6pmo=";
    });
    date = "2022-05-02";
  };
  tuc = {
    pname = "tuc";
    version = "2b73054dde91e7efb0985cca322acd7c5f1093e0";
    src = fetchFromGitHub ({
      owner = "riquito";
      repo = "tuc";
      rev = "2b73054dde91e7efb0985cca322acd7c5f1093e0";
      fetchSubmodules = false;
      sha256 = "sha256-xzBseHMejxPFqQf3dmxoFv+dfxMrLUJA762latUp9TM=";
    });
    date = "2022-10-21";
  };
  watchexec-simple = {
    pname = "watchexec-simple";
    version = "2ce685a1804d6ffed2c1c20abff2a9cf648c7188";
    src = fetchFromGitHub ({
      owner = "kurtbuilds";
      repo = "watchexec-simple";
      rev = "2ce685a1804d6ffed2c1c20abff2a9cf648c7188";
      fetchSubmodules = false;
      sha256 = "sha256-AOweMMWuJx9mtSss5Iett0fTVBoZrjCaDGnzOO8RrMw=";
    });
    date = "2022-11-24";
  };
  zeek-language-server = {
    pname = "zeek-language-server";
    version = "999c65ef7e2ecf7b692cf19d54880ef63e3b8c4b";
    src = fetchFromGitHub ({
      owner = "bbannier";
      repo = "zeek-language-server";
      rev = "999c65ef7e2ecf7b692cf19d54880ef63e3b8c4b";
      fetchSubmodules = true;
      sha256 = "sha256-bB/XCfr/uMQupi7ps21s/vYZx1AgI+25q95L+C2TfEI=";
    });
    date = "2022-12-10";
  };
}
