# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  choochoo = {
    pname = "choochoo";
    version = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
    src = fetchFromGitHub {
      owner = "andrewcooke";
      repo = "choochoo";
      rev = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
      fetchSubmodules = false;
      sha256 = "sha256-/PjfY1thoILxpu3/PTmFRfzR4eFgraLbTXpVM54GXJk=";
    };
    date = "2021-09-12";
  };
  cliche = {
    pname = "cliche";
    version = "82c4f9dc1644f34077ab0995dda3bf7dcc2946a4";
    src = fetchFromGitHub {
      owner = "kootenpv";
      repo = "cliche";
      rev = "82c4f9dc1644f34077ab0995dda3bf7dcc2946a4";
      fetchSubmodules = false;
      sha256 = "sha256-rM6HPITGKrHElBrDoYrfm5ivXa+6SGjPbIbWVrFTwpA=";
    };
    date = "2023-12-21";
  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
    src = fetchFromGitHub {
      owner = "esnet";
      repo = "eZeeKonfigurator";
      rev = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
      fetchSubmodules = false;
      sha256 = "sha256-K7PLVVesjv27dhYyRaWItfnsh+p6FTMFOXVE576a01I=";
    };
    date = "2022-07-05";
  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchFromGitHub {
      owner = "esnet";
      repo = "eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      sha256 = "sha256-b2QqmduoyohAIOJnZP/Vnt9FdmoOebDfmaTs5SNVoAg=";
    };
    date = "2021-07-01";
  };
  elastalert2 = {
    pname = "elastalert2";
    version = "436d3386652d1f9367368a7910943ee00986cc34";
    src = fetchFromGitHub {
      owner = "jertel";
      repo = "elastalert2";
      rev = "436d3386652d1f9367368a7910943ee00986cc34";
      fetchSubmodules = false;
      sha256 = "sha256-TDWG7losdoTy4wdGP8ueM+ZQoT/nQaVcUNYXP6irLV4=";
    };
    date = "2023-12-17";
  };
  polars = {
    pname = "polars";
    version = "py-0.20.2";
    src = fetchFromGitHub {
      owner = "pola-rs";
      repo = "polars";
      rev = "py-0.20.2";
      fetchSubmodules = false;
      sha256 = "sha256-NZsM3y9xNX9C3/lm+pXgfxvjFy2KgvPXufc6i4eXP0A=";
    };
  };
  sh = {
    pname = "sh";
    version = "2.0.6";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/sh/sh-2.0.6.tar.gz";
      sha256 = "sha256-mymY8xPyAcd34sAGHwsTZ0lwl+8TOIWVvhR+KgC/e6E=";
    };
  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchFromGitHub {
      owner = "NullHypothesis";
      repo = "sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      sha256 = "sha256-vIOibQuMauVhkxgR9QaL+pbocY7xgyamMeOhtKmye70=";
    };
    date = "2019-03-26";
  };
  vailyn = {
    pname = "vailyn";
    version = "v3.3.2-1";
    src = fetchFromGitHub {
      owner = "VainlyStrain";
      repo = "Vailyn";
      rev = "v3.3.2-1";
      fetchSubmodules = false;
      sha256 = "sha256-eHnqfL6Nt0FDyIoZ4RhwB29h3r6ctVQKAGCeZkOk5yo=";
    };
  };
  vault-cli = {
    pname = "vault-cli";
    version = "0142476bcfda52876951f49b0990ac1d85377d3a";
    src = fetchFromGitHub {
      owner = "peopledoc";
      repo = "vault-cli";
      rev = "0142476bcfda52876951f49b0990ac1d85377d3a";
      fetchSubmodules = false;
      sha256 = "sha256-/YNBI1IknygmqKy5JMCS63AX581YY5wqE1KN75rBPH0=";
    };
    date = "2022-01-27";
  };
}
