# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  aim = {
    pname = "aim";
    version = "v3.13.1";
    src = fetchFromGitHub ({
      owner = "aimhubio";
      repo = "aim";
      rev = "v3.13.1";
      fetchSubmodules = false;
      sha256 = "sha256-bvyOqzYZx1D+7Bai3h9DaDpMjy6XcqTu5Z5V3g4gOog=";
    });
  };
  brim = {
    pname = "brim";
    version = "0.31.0";
    src = fetchurl {
      url = "https://github.com/brimdata/brim/releases/download/v0.31.0/Brim-0.31.0.deb";
      sha256 = "sha256-ouJB8DHK5IZdPCZ9/r7ah7qaSWh5L05EHvklaBhfz1A=";
    };
  };
  broker = {
    pname = "broker";
    version = "5ad9e8ed91c3e069f7442fb6687f0ccc2fcbd805";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "broker";
      rev = "5ad9e8ed91c3e069f7442fb6687f0ccc2fcbd805";
      fetchSubmodules = true;
      sha256 = "sha256-cp/dNVNOUDdExcEO0e/sYztmY58VGLiIv1/OQ8J+k4M=";
    });
  };
  broker-to-json = {
    pname = "broker-to-json";
    version = "v_02";
    src = fetchFromGitHub ({
      owner = "grigorescu";
      repo = "broker-to-json";
      rev = "v_02";
      fetchSubmodules = false;
      sha256 = "sha256-SROcIR2P5ixk4yDVwkUJczdbuU4STpmTyLNBCj6dEtg=";
    });
  };
  btest = {
    pname = "btest";
    version = "0.71";
    src = fetchurl {
      url = "https://pypi.io/packages/source/b/btest/btest-0.71.tar.gz";
      sha256 = "sha256-17JpGNgq917qNp1snF2I6teeid9RxCaM6nSYiQh9Ocw=";
    };
  };
  caretaker = {
    pname = "caretaker";
    version = "v0.2.4";
    src = fetchFromGitHub ({
      owner = "grego";
      repo = "caretaker";
      rev = "v0.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-xP3AfwD9Er0TolAN65NfC2GkC1KlpcyV1J68KjBBEwU=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./caretaker-v0.2.4/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  choochoo = {
    pname = "choochoo";
    version = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
    src = fetchFromGitHub ({
      owner = "andrewcooke";
      repo = "choochoo";
      rev = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
      fetchSubmodules = false;
      sha256 = "sha256-/PjfY1thoILxpu3/PTmFRfzR4eFgraLbTXpVM54GXJk=";
    });
  };
  cliche = {
    pname = "cliche";
    version = "a13b7e9bf0c0e4f4073da03ae7f2273055232711";
    src = fetchFromGitHub ({
      owner = "kootenpv";
      repo = "cliche";
      rev = "a13b7e9bf0c0e4f4073da03ae7f2273055232711";
      fetchSubmodules = false;
      sha256 = "sha256-wGBDylebd8DREU8LxgAy+r1MvuXlWbMRSspmMN466jQ=";
    });
  };
  container-structure-test = {
    pname = "container-structure-test";
    version = "3e6fe0f52eeebfe9cd2962b27d40cc2927fe30ec";
    src = fetchFromGitHub ({
      owner = "GoogleContainerTools";
      repo = "container-structure-test";
      rev = "3e6fe0f52eeebfe9cd2962b27d40cc2927fe30ec";
      fetchSubmodules = false;
      sha256 = "sha256-hMbBPNbrAlDt401rZqIg1t+3p3DYSI6JeeZ3bQI1z1E=";
    });
  };
  durationpy = {
    pname = "durationpy";
    version = "0.5";
    src = fetchurl {
      url = "https://pypi.io/packages/source/d/durationpy/durationpy-0.5.tar.gz";
      sha256 = "sha256-XvlBa1J7UNci80ZVvs+3Xkkijrgvh7hV7RkRszFLVAg=";
    };
  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator";
      rev = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
      fetchSubmodules = false;
      sha256 = "sha256-K7PLVVesjv27dhYyRaWItfnsh+p6FTMFOXVE576a01I=";
    });
  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      sha256 = "sha256-b2QqmduoyohAIOJnZP/Vnt9FdmoOebDfmaTs5SNVoAg=";
    });
  };
  elastalert2 = {
    pname = "elastalert2";
    version = "6f5543692e15f779f974a48db597c6cc634e2276";
    src = fetchFromGitHub ({
      owner = "jertel";
      repo = "elastalert2";
      rev = "6f5543692e15f779f974a48db597c6cc634e2276";
      fetchSubmodules = false;
      sha256 = "sha256-Ioatd7I+poFOB37c7BXHP9NSB3glsWsC7tm3wHk+RTA=";
    });
  };
  fastai = {
    pname = "fastai";
    version = "9467ea7c74b555fbc3a89e068a0d9626e1e58256";
    src = fetchFromGitHub ({
      owner = "fastai";
      repo = "fastai";
      rev = "9467ea7c74b555fbc3a89e068a0d9626e1e58256";
      fetchSubmodules = false;
      sha256 = "sha256-LNBSQAf1u7KFOFYuwRhqQerNV5r4XZkhFTAhmEip2WY=";
    });
  };
  fastcore = {
    pname = "fastcore";
    version = "9857cf4df0cc67ffdc635f9a68d404067a5e95da";
    src = fetchFromGitHub ({
      owner = "fastai";
      repo = "fastcore";
      rev = "9857cf4df0cc67ffdc635f9a68d404067a5e95da";
      fetchSubmodules = false;
      sha256 = "sha256-/pjm8Ym8Wz6CQz/ap7/HdkgyWD1LjpLut9KTpJShMAQ=";
    });
  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.3";
    src = fetchurl {
      url = "https://pypi.io/packages/source/f/fastprogress/fastprogress-1.0.3.tar.gz";
      sha256 = "sha256-ehfStDiJD4OMBI7vzjLE3tRxl+zI6gQs7MM9PeuAIvU=";
    };
  };
  ghq = {
    pname = "ghq";
    version = "8f948f2d8b69cd346afc6331f58e673230df5b5e";
    src = fetchFromGitHub ({
      owner = "x-motemen";
      repo = "ghq";
      rev = "8f948f2d8b69cd346afc6331f58e673230df5b5e";
      fetchSubmodules = false;
      sha256 = "sha256-jxqTM4nn5PpIDkCttRI6WzJ5eAhuM8Z2fIBsO6IJ2YA=";
    });
  };
  go-nfsd = {
    pname = "go-nfsd";
    version = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
    src = fetchFromGitHub ({
      owner = "mit-pdos";
      repo = "go-nfsd";
      rev = "a019f4d17fe0c5d02404788dbef39bc9f885e521";
      fetchSubmodules = false;
      sha256 = "sha256-+bcRGlJhQSWPLVgSmAbP0Kh6mqCgmnZZksmQV7cVG3g=";
    });
  };
  gst = {
    pname = "gst";
    version = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
    src = fetchFromGitHub ({
      owner = "uetchy";
      repo = "gst";
      rev = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
      fetchSubmodules = false;
      sha256 = "sha256-NhbGHTYucfqCloVirkaDlAtQfhWP2cw4I+t/ysvvkR0=";
    });
  };
  nix-unstable-installer = {
    pname = "nix-unstable-installer";
    version = "nix-2.12.0pre20220901_4823067";
    src = fetchurl {
      url = "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20220901_4823067/install";
      sha256 = "sha256-tOh9n1AQPE+1uFQyZv10ywXOD6ytL8HiXLo4CO8PndQ=";
    };
  };
  nvdtools = {
    pname = "nvdtools";
    version = "1903161849b5da88fe3482d2e4ed258320c195ae";
    src = fetchFromGitHub ({
      owner = "facebookincubator";
      repo = "nvdtools";
      rev = "1903161849b5da88fe3482d2e4ed258320c195ae";
      fetchSubmodules = false;
      sha256 = "sha256-TwBuKd7zmbwbgBiP8c7vEj4i4VoP1p5A+ni0SODD2xA=";
    });
  };
  osquery = {
    pname = "osquery";
    version = "5.2.2";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.2.2/osquery_5.2.2-1.linux_amd64.deb";
      sha256 = "sha256-i8DK5bNQlLoeAhatT5qRGMCFDgP/ArDbQKs0fPdccWM=";
    };
  };
  py-tree-sitter = {
    pname = "py-tree-sitter";
    version = "d3016edac2c33ce647653d896fbfb435ac2a6245";
    src = fetchFromGitHub ({
      owner = "tree-sitter";
      repo = "py-tree-sitter";
      rev = "d3016edac2c33ce647653d896fbfb435ac2a6245";
      fetchSubmodules = true;
      sha256 = "sha256-mdV5zGvVI1MltmOD1BtXxsKB/yigk8d56WwLlX6Uizg=";
    });
  };
  sslproxy = {
    pname = "sslproxy";
    version = "e456f56001e4dd99972a0430122a5782538a60fd";
    src = fetchFromGitHub ({
      owner = "sonertari";
      repo = "SSLproxy";
      rev = "e456f56001e4dd99972a0430122a5782538a60fd";
      fetchSubmodules = false;
      sha256 = "sha256-HH2QMBfX907oqdd+OlY0Wai/fOsrA5tI/BWW5Vj6pmo=";
    });
  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchFromGitHub ({
      owner = "NullHypothesis";
      repo = "sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      sha256 = "sha256-vIOibQuMauVhkxgR9QaL+pbocY7xgyamMeOhtKmye70=";
    });
  };
  tc-redirect-tap = {
    pname = "tc-redirect-tap";
    version = "f2af445210939e364605b4d839015ee3676ac8cd";
    src = fetchFromGitHub ({
      owner = "awslabs";
      repo = "tc-redirect-tap";
      rev = "f2af445210939e364605b4d839015ee3676ac8cd";
      fetchSubmodules = false;
      sha256 = "sha256-8DH3sOZeUkXgv6rd02JYyudwztCM5BzvQqOizgQ7MRw=";
    });
  };
  tuc = {
    pname = "tuc";
    version = "5c5c1428355f52646e6655845131416aad9a55f8";
    src = fetchFromGitHub ({
      owner = "riquito";
      repo = "tuc";
      rev = "5c5c1428355f52646e6655845131416aad9a55f8";
      fetchSubmodules = false;
      sha256 = "sha256-coTYSzHFlJQO/kT0xs/IPknF2MFVLw7p004JgK8yutE=";
    });
  };
  vailyn = {
    pname = "vailyn";
    version = "v3.3.2-1";
    src = fetchFromGitHub ({
      owner = "VainlyStrain";
      repo = "Vailyn";
      rev = "v3.3.2-1";
      fetchSubmodules = false;
      sha256 = "sha256-eHnqfL6Nt0FDyIoZ4RhwB29h3r6ctVQKAGCeZkOk5yo=";
    });
  };
  vault-cli = {
    pname = "vault-cli";
    version = "0142476bcfda52876951f49b0990ac1d85377d3a";
    src = fetchFromGitHub ({
      owner = "peopledoc";
      repo = "vault-cli";
      rev = "0142476bcfda52876951f49b0990ac1d85377d3a";
      fetchSubmodules = false;
      sha256 = "sha256-/YNBI1IknygmqKy5JMCS63AX581YY5wqE1KN75rBPH0=";
    });
  };
  watchexec-simple = {
    pname = "watchexec-simple";
    version = "61387ab273eb6e71503c3e7d042e1a319fb6cfa5";
    src = fetchFromGitHub ({
      owner = "kurtbuilds";
      repo = "watchexec-simple";
      rev = "61387ab273eb6e71503c3e7d042e1a319fb6cfa5";
      fetchSubmodules = false;
      sha256 = "sha256-okQ/63hDC/KiBanHq4CiuEfH3y45mTShNfRG2DOqrMc=";
    });
  };
  zat = {
    pname = "zat";
    version = "fed88c4310cf70c8b01c9a7eb0918b8c4d117e77";
    src = fetchFromGitHub ({
      owner = "SuperCowPowers";
      repo = "zat";
      rev = "fed88c4310cf70c8b01c9a7eb0918b8c4d117e77";
      fetchSubmodules = false;
      sha256 = "sha256-8uydkQkD5M4jFCmMLNkJDdFILYLzvJuLFfbNPLNHmHE=";
    });
  };
  zed = {
    pname = "zed";
    version = "1c906e49382a15c02818353a69b29fa59e46c5d4";
    src = fetchFromGitHub ({
      owner = "brimdata";
      repo = "zed";
      rev = "1c906e49382a15c02818353a69b29fa59e46c5d4";
      fetchSubmodules = false;
      sha256 = "sha256-VZplD6hYabaxTU2qoR1zuOiceZiGhBvqrUTTLRLPbNs=";
    });
  };
  zeek-language-server = {
    pname = "zeek-language-server";
    version = "dec977425c679889f0c1b662d4e55b474450fe2f";
    src = fetchFromGitHub ({
      owner = "bbannier";
      repo = "zeek-language-server";
      rev = "dec977425c679889f0c1b662d4e55b474450fe2f";
      fetchSubmodules = true;
      sha256 = "sha256-2BHV8v4jm8Zhaa9+PiK/B0SV912OXC8ft8TpjUjshZA=";
    });
  };
  zeekscript = {
    pname = "zeekscript";
    version = "c321befa9e49126974578eceea40c6f27be9a616";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeekscript";
      rev = "c321befa9e49126974578eceea40c6f27be9a616";
      fetchSubmodules = true;
      sha256 = "sha256-j4+trMH+YH37YHL9rxFLKTjkU9HREEGGoPDJO3UlaJ4=";
    });
  };
}
