# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  brim = {
    pname = "brim";
    version = "0.26.0";
    src = fetchurl {
      url = "https://github.com/brimdata/brim/releases/download/v0.26.0/Brim-0.26.0.deb";
      sha256 = "sha256-A5hjJpUKHTI19I56o7m9ycuKLhdMZEUVJvdRT8HuWZc=";
    };
  };
  broker = {
    pname = "broker";
    version = "47cac80cbe1e1bde8e3b425903e50d62715972a2";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "broker";
      rev = "47cac80cbe1e1bde8e3b425903e50d62715972a2";
      fetchSubmodules = true;
      sha256 = "sha256-A3m+7s6gHgZJl5NkYNRtr/8Yzq6db4xH9v9UiJ126sA=";
    });
  };
  broker-to-json = {
    pname = "broker-to-json";
    version = "v_02";
    src = fetchFromGitHub ({
      owner = "grigorescu";
      repo = "broker-to-json";
      rev = "v_02";
      fetchSubmodules = false;
      sha256 = "sha256-SROcIR2P5ixk4yDVwkUJczdbuU4STpmTyLNBCj6dEtg=";
    });
  };
  btest = {
    pname = "btest";
    version = "0.70";
    src = fetchurl {
      url = "https://pypi.io/packages/source/b/btest/btest-0.70.tar.gz";
      sha256 = "sha256-JKyCnUyXM+O6C8W5loe9aDDWgF/6lZocvRCNJpz6ULk=";
    };
  };
  choochoo = {
    pname = "choochoo";
    version = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
    src = fetchFromGitHub ({
      owner = "andrewcooke";
      repo = "choochoo";
      rev = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
      fetchSubmodules = false;
      sha256 = "sha256-/PjfY1thoILxpu3/PTmFRfzR4eFgraLbTXpVM54GXJk=";
    });
  };
  clx = {
    pname = "clx";
    version = "1c2c5f9e776d6b2e8399f422cd9a2fc4394828bf";
    src = fetchFromGitHub ({
      owner = "rapidsai";
      repo = "clx";
      rev = "1c2c5f9e776d6b2e8399f422cd9a2fc4394828bf";
      fetchSubmodules = false;
      sha256 = "sha256-GHnlMQuTJ4oxZ4unMKfvnf16ipsmjTo6xE7tXN/iD1I=";
    });
  };
  cnmem = {
    pname = "cnmem";
    version = "37896cc9bfc6536a8c878a1e675835c22d827821";
    src = fetchFromGitHub ({
      owner = "NVIDIA";
      repo = "cnmem";
      rev = "37896cc9bfc6536a8c878a1e675835c22d827821";
      fetchSubmodules = false;
      sha256 = "sha256-Xpr0idhBhCxFC0yDWpZwwD29FRMGdTrD5RzgluwuonM=";
    });
  };
  cudf = {
    pname = "cudf";
    version = "77c6f1d0e0509f62688147a33408485062ab0ab3";
    src = fetchFromGitHub ({
      owner = "rapidsai";
      repo = "cudf";
      rev = "77c6f1d0e0509f62688147a33408485062ab0ab3";
      fetchSubmodules = false;
      sha256 = "sha256-eiCE33K0RflB8tsNl+t/y+3YhfDBYYf5fngcBTUWEcI=";
    });
  };
  durationpy = {
    pname = "durationpy";
    version = "0.5";
    src = fetchurl {
      url = "https://pypi.io/packages/source/d/durationpy/durationpy-0.5.tar.gz";
      sha256 = "sha256-XvlBa1J7UNci80ZVvs+3Xkkijrgvh7hV7RkRszFLVAg=";
    };
  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "51bb45163e90a1d328a3fb3f44f95b8801e70687";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator";
      rev = "51bb45163e90a1d328a3fb3f44f95b8801e70687";
      fetchSubmodules = false;
      sha256 = "sha256-AgY2x5lxj47oUpUXcUhEINVGd0iMOOvVhzQOiUIVMwk=";
    });
  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      sha256 = "sha256-b2QqmduoyohAIOJnZP/Vnt9FdmoOebDfmaTs5SNVoAg=";
    });
  };
  elastalert2 = {
    pname = "elastalert2";
    version = "18f435fd07f2818b9e96f2871b4bdf3762cf9cfc";
    src = fetchFromGitHub ({
      owner = "jertel";
      repo = "elastalert2";
      rev = "18f435fd07f2818b9e96f2871b4bdf3762cf9cfc";
      fetchSubmodules = false;
      sha256 = "sha256-7RQrrcCtUERvWSxL9HXybZzZY7OxByv2Gtm8mcASDyw=";
    });
  };
  fastai = {
    pname = "fastai";
    version = "f8b74ef5b320512a2bb4a6c3cb17a5e917b7d6a3";
    src = fetchFromGitHub ({
      owner = "fastai";
      repo = "fastai";
      rev = "f8b74ef5b320512a2bb4a6c3cb17a5e917b7d6a3";
      fetchSubmodules = false;
      sha256 = "sha256-BijfokHrSN3JmbLjKrBUf8/h3KSWrKHftmlVcNjjHww=";
    });
  };
  fastcore = {
    pname = "fastcore";
    version = "5093ae0d42c1db9d685f5600442c1dd7e183edc3";
    src = fetchFromGitHub ({
      owner = "fastai";
      repo = "fastcore";
      rev = "5093ae0d42c1db9d685f5600442c1dd7e183edc3";
      fetchSubmodules = false;
      sha256 = "sha256-FJnmuPLKo0CsdVU28kAKKo4RCfH8ixE5VjfmvlDUO2Y=";
    });
  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.0";
    src = fetchurl {
      url = "https://pypi.io/packages/source/f/fastprogress/fastprogress-1.0.0.tar.gz";
      sha256 = "sha256-ieKKwdKlQSqrGO4/Pf0e6LXB8vekTQrdDQ1PafAZG/4=";
    };
  };
  ghq = {
    pname = "ghq";
    version = "0e02db0b9a7a6773e503dd99bdabca49bfdf67af";
    src = fetchFromGitHub ({
      owner = "x-motemen";
      repo = "ghq";
      rev = "0e02db0b9a7a6773e503dd99bdabca49bfdf67af";
      fetchSubmodules = false;
      sha256 = "sha256-chpaac01Wbdp+sA38O50iGVGt6zxA2N3/NUzhsptSVs=";
    });
  };
  go-nfsd = {
    pname = "go-nfsd";
    version = "bb1dc61f5ca3f77c93164a94023548ff2fa5ec07";
    src = fetchFromGitHub ({
      owner = "mit-pdos";
      repo = "go-nfsd";
      rev = "bb1dc61f5ca3f77c93164a94023548ff2fa5ec07";
      fetchSubmodules = false;
      sha256 = "sha256-V3x8jtQudftrIrXS8ZrVlzacUIC/TBpm0NEyLE636LI=";
    });
  };
  gst = {
    pname = "gst";
    version = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
    src = fetchFromGitHub ({
      owner = "uetchy";
      repo = "gst";
      rev = "b4af138c9a2dfc6bb04d853cd045eff9a5d8b608";
      fetchSubmodules = false;
      sha256 = "sha256-NhbGHTYucfqCloVirkaDlAtQfhWP2cw4I+t/ysvvkR0=";
    });
  };
  nvdtools = {
    pname = "nvdtools";
    version = "e3af1166b05d4773b7aa4eb83e0ccd93e928eb3a";
    src = fetchFromGitHub ({
      owner = "facebookincubator";
      repo = "nvdtools";
      rev = "e3af1166b05d4773b7aa4eb83e0ccd93e928eb3a";
      fetchSubmodules = false;
      sha256 = "sha256-EHUo5V+LlWNErVIw39d8brqJ6PIUgI29HOWVJ13YAkw=";
    });
  };
  osquery = {
    pname = "osquery";
    version = "5.0.1";
    src = fetchurl {
      url = "https://github.com/osquery/osquery/releases/download/5.0.1/osquery_5.0.1-1.linux_amd64.deb";
      sha256 = "sha256-2TwYYDLZVcJGFIFug7FFNNedEMB5kw6cvB1Ap5HLFbQ=";
    };
  };
  rmm = {
    pname = "rmm";
    version = "c07f1c8a38394bd60dea28a8bbaad439172e6f29";
    src = fetchFromGitHub ({
      owner = "rapidsai";
      repo = "rmm";
      rev = "c07f1c8a38394bd60dea28a8bbaad439172e6f29";
      fetchSubmodules = false;
      sha256 = "sha256-Tn1RSVfS4ipDV5z6hrLIV0SdujnNcmEdBzJprnSbXCc=";
    });
  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchFromGitHub ({
      owner = "NullHypothesis";
      repo = "sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      sha256 = "sha256-vIOibQuMauVhkxgR9QaL+pbocY7xgyamMeOhtKmye70=";
    });
  };
  zat = {
    pname = "zat";
    version = "7f0de8bb052e8c84ab9bd00f195514d957eac9ec";
    src = fetchFromGitHub ({
      owner = "SuperCowPowers";
      repo = "zat";
      rev = "7f0de8bb052e8c84ab9bd00f195514d957eac9ec";
      fetchSubmodules = false;
      sha256 = "sha256-LHxBzb2glKaseC4RIS501qjKVSKY8zv9dl+llmY6P84=";
    });
  };
  zed = {
    pname = "zed";
    version = "eaf43a6d3af6e0cb0cef75d0dcd1cfb7ffe1ac13";
    src = fetchFromGitHub ({
      owner = "brimdata";
      repo = "zed";
      rev = "eaf43a6d3af6e0cb0cef75d0dcd1cfb7ffe1ac13";
      fetchSubmodules = false;
      sha256 = "sha256-3uzhWMZSs9roUpwtcMDLnr3t3EBYEmkPx1gLkeLaKbc=";
    });
  };
}
