# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aim = {
    pname = "aim";
    version = "v3.14.4";
    src = fetchFromGitHub ({
      owner = "aimhubio";
      repo = "aim";
      rev = "v3.14.4";
      fetchSubmodules = false;
      sha256 = "sha256-MWGihKwy6fOEEF1pk13w7WnuvKtSz912NRs7DhV9FqU=";
    });
  };
  broker-to-json = {
    pname = "broker-to-json";
    version = "v_02";
    src = fetchFromGitHub ({
      owner = "grigorescu";
      repo = "broker-to-json";
      rev = "v_02";
      fetchSubmodules = false;
      sha256 = "sha256-SROcIR2P5ixk4yDVwkUJczdbuU4STpmTyLNBCj6dEtg=";
    });
  };
  btest = {
    pname = "btest";
    version = "0.71";
    src = fetchurl {
      url = "https://pypi.io/packages/source/b/btest/btest-0.71.tar.gz";
      sha256 = "sha256-17JpGNgq917qNp1snF2I6teeid9RxCaM6nSYiQh9Ocw=";
    };
  };
  choochoo = {
    pname = "choochoo";
    version = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
    src = fetchFromGitHub ({
      owner = "andrewcooke";
      repo = "choochoo";
      rev = "29750cdb9f87dc7a4b6e423df6e805e14ecae5e1";
      fetchSubmodules = false;
      sha256 = "sha256-/PjfY1thoILxpu3/PTmFRfzR4eFgraLbTXpVM54GXJk=";
    });
    date = "2021-09-12";
  };
  cliche = {
    pname = "cliche";
    version = "a13b7e9bf0c0e4f4073da03ae7f2273055232711";
    src = fetchFromGitHub ({
      owner = "kootenpv";
      repo = "cliche";
      rev = "a13b7e9bf0c0e4f4073da03ae7f2273055232711";
      fetchSubmodules = false;
      sha256 = "sha256-wGBDylebd8DREU8LxgAy+r1MvuXlWbMRSspmMN466jQ=";
    });
    date = "2022-05-09";
  };
  durationpy = {
    pname = "durationpy";
    version = "0.5";
    src = fetchurl {
      url = "https://pypi.io/packages/source/d/durationpy/durationpy-0.5.tar.gz";
      sha256 = "sha256-XvlBa1J7UNci80ZVvs+3Xkkijrgvh7hV7RkRszFLVAg=";
    };
  };
  eZeeKonfigurator = {
    pname = "eZeeKonfigurator";
    version = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator";
      rev = "d4b0d2382be550e2af46aeaf0ac02aab9b694668";
      fetchSubmodules = false;
      sha256 = "sha256-K7PLVVesjv27dhYyRaWItfnsh+p6FTMFOXVE576a01I=";
    });
    date = "2022-07-05";
  };
  eZeeKonfigurator_client = {
    pname = "eZeeKonfigurator_client";
    version = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "eZeeKonfigurator_client";
      rev = "efbe39bb1e40a0332d37c3291ee3c8af1ff7678e";
      fetchSubmodules = false;
      sha256 = "sha256-b2QqmduoyohAIOJnZP/Vnt9FdmoOebDfmaTs5SNVoAg=";
    });
    date = "2021-07-01";
  };
  elastalert2 = {
    pname = "elastalert2";
    version = "ac6dfebaa567f55f187255c3c2309ebbc25ee867";
    src = fetchFromGitHub ({
      owner = "jertel";
      repo = "elastalert2";
      rev = "ac6dfebaa567f55f187255c3c2309ebbc25ee867";
      fetchSubmodules = false;
      sha256 = "sha256-jdl8EfH7FgFN1B7twLWjkiP9O5cZMrJG+yGTu7MRDfA=";
    });
    date = "2022-11-12";
  };
  fastprogress = {
    pname = "fastprogress";
    version = "1.0.3";
    src = fetchurl {
      url = "https://pypi.io/packages/source/f/fastprogress/fastprogress-1.0.3.tar.gz";
      sha256 = "sha256-ehfStDiJD4OMBI7vzjLE3tRxl+zI6gQs7MM9PeuAIvU=";
    };
  };
  py-tree-sitter = {
    pname = "py-tree-sitter";
    version = "d3016edac2c33ce647653d896fbfb435ac2a6245";
    src = fetchFromGitHub ({
      owner = "tree-sitter";
      repo = "py-tree-sitter";
      rev = "d3016edac2c33ce647653d896fbfb435ac2a6245";
      fetchSubmodules = true;
      sha256 = "sha256-mdV5zGvVI1MltmOD1BtXxsKB/yigk8d56WwLlX6Uizg=";
    });
    date = "2022-09-05";
  };
  sh = {
    pname = "sh";
    version = "1.14.3";
    src = fetchurl {
      url = "https://pypi.io/packages/source/s/sh/sh-1.14.3.tar.gz";
      sha256 = "sha256-5ARbbHMtnOddVxx59awiNO3Zrk9fqdWbCXBQgr3KGMc=";
    };
  };
  sybilhunter = {
    pname = "sybilhunter";
    version = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
    src = fetchFromGitHub ({
      owner = "NullHypothesis";
      repo = "sybilhunter";
      rev = "2f0a8f09308f7de51ce1095353f4af82a8a15f88";
      fetchSubmodules = false;
      sha256 = "sha256-vIOibQuMauVhkxgR9QaL+pbocY7xgyamMeOhtKmye70=";
    });
    date = "2019-03-26";
  };
  vailyn = {
    pname = "vailyn";
    version = "v3.3.2-1";
    src = fetchFromGitHub ({
      owner = "VainlyStrain";
      repo = "Vailyn";
      rev = "v3.3.2-1";
      fetchSubmodules = false;
      sha256 = "sha256-eHnqfL6Nt0FDyIoZ4RhwB29h3r6ctVQKAGCeZkOk5yo=";
    });
  };
  vault-cli = {
    pname = "vault-cli";
    version = "0142476bcfda52876951f49b0990ac1d85377d3a";
    src = fetchFromGitHub ({
      owner = "peopledoc";
      repo = "vault-cli";
      rev = "0142476bcfda52876951f49b0990ac1d85377d3a";
      fetchSubmodules = false;
      sha256 = "sha256-/YNBI1IknygmqKy5JMCS63AX581YY5wqE1KN75rBPH0=";
    });
    date = "2022-01-27";
  };
  zat = {
    pname = "zat";
    version = "e458123cd7a02336102147bba7f34c5a641f45c3";
    src = fetchFromGitHub ({
      owner = "SuperCowPowers";
      repo = "zat";
      rev = "e458123cd7a02336102147bba7f34c5a641f45c3";
      fetchSubmodules = false;
      sha256 = "sha256-8kI1Lz1zJIIXMhddnw0b132bvApChNSzWGJRri2ElDc=";
    });
    date = "2022-11-12";
  };
  zed = {
    pname = "zed";
    version = "d86f8b13c93c8e9b8608fa6f83fa2fec1c019ae0";
    src = fetchFromGitHub ({
      owner = "brimdata";
      repo = "zed";
      rev = "d86f8b13c93c8e9b8608fa6f83fa2fec1c019ae0";
      fetchSubmodules = false;
      sha256 = "sha256-htvD9/YFC4UoWt1Npn1lFokGXu4Dj1/pYzRog7qXldw=";
    });
    date = "2022-11-15";
  };
  zeekscript = {
    pname = "zeekscript";
    version = "c321befa9e49126974578eceea40c6f27be9a616";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeekscript";
      rev = "c321befa9e49126974578eceea40c6f27be9a616";
      fetchSubmodules = true;
      sha256 = "sha256-j4+trMH+YH37YHL9rxFLKTjkU9HREEGGoPDJO3UlaJ4=";
    });
    date = "2022-09-08";
  };
}
